### ISSUE TITLE
Nginx | Modsecurity 3.0 | CRS 3.0 no startup

### ISSUE THREAD

**Issue by Schoomee** [SpiderLabs/owasp-modsecurity-crs#1034]
hello,

I'm trying desperately to start Nginx with the OWASP CRS 3.0 rules but I get an error:

"Nginx: [emerg]" modsecurity_rules_file "Rules error directive. File: /etc/nginx/modsec/owasp-modsecurity-crs/crs-setup.conf. Line: 96. Column: 43. SecCollectionTimeout is not yet supported. in /etc/nginx/nginx.conf:38 »

The test of a simple rule works well:
"ARGS SecRule: testparam" @contains test "" id: 1234, deny, status: 403 "
I found the "forbiden" in the logs.

The versions used:
Nginx: 1.13.9
Modsecurity: 3.0 "v3 / master"
ModSecurity-nginx
Debian 9

I tried several branchs / versions without results ...

**Comment by dune73** [comment]
Hi @Schoomee, thanks for reporting.

As it happens, I faced the same problem on Saturday. I resolved it by compiling nginx, the connector and modsec anew from scratch and following nginx.org's ModSec integration guide. Then it suddenly worked.

If it does not in your case, I fear it is more of a ModSecurity than a CRS problem.

**Comment by csanders-git** [comment]
Please reopen if @dune73's solution does not solve the issue.

**Comment by victorhora** [comment]
@Schoomee @dune73 this happened due to a [recent change](https://github.com/SpiderLabs/ModSecurity/commit/64ce41280d0f7d85c5ea851ca75251e3720070d9#diff-962a547bd453ba5f839067225f72cae5R1703) on the parser to warn users on configuration directives that are being worked on for v3.

Commenting out the SecCollectionTimeout directive on [crs-setup.conf](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/crs-setup.conf.example#L708) solves the problem temporarily.

I'm suggesting a [small change to the parser](https://github.com/SpiderLabs/ModSecurity/compare/v3/master...v3/dev/fix-seccol_timeout_err_crs?expand=1) to ensure CRS compatibility between v2 and v3. You can also choose to apply this change on the code for now. I'll update here when it gets merged to main.

**Comment by Schoomee** [comment]
@dune73  thank you for your answer, I have the same installation guide on the official website Nginx:
https://www.nginx.com/blog/compiling-and-installing-modsecurity-for-open-source-nginx/
and
https://docs.nginx.com/nginx-waf/admin-guide/nginx-plus-modsecurity-waf-owasp-crs/
but still with the same problem ...
Currently it works with the version of ModSecurity 2.9x
from the Nginx logs:
'for nginx (STABLE) /2.9.0 (http://www.modsecurity.org/) configured.'

@victorhora thanks for your help, i will recompile nginx with ModSec3 3.0 / CRS3 by following your advice.

I keep you informed.
