### ISSUE TITLE
False positives on Ghost blog

### ISSUE THREAD

**Issue by theMiddleBlue** [SpiderLabs/owasp-modsecurity-crs#1295]
I'm creating an EXCLUSION rule set to handle all FPs for a default Ghost Blog installation (https://ghost.org/) in my WAF nodes. At the time, all FPs seems to be related to the "admin API". For example, when a user changes something on his profile:

```
PUT /ghost/api/v2/admin/users/<md5>/?include=roles HTTP/1.1
{ ...  json encoded content ... }
```

matches the following rules:
```
Method is not allowed by policy Rule ID: 911100
OS File Access Attempt Rule ID: 930120
```

The hardest thing to exclude is when a user creates a new post because it depends on what he writes on it... in theory, it could fire the whole rule set :)

```
PUT /ghost/api/v2/admin/posts/<md5>/?include=authors,tags,authors.roles HTTP/1.1

{"posts":[{ ... }]}
```

it could match:
```
Method is not allowed by policy Rule ID: 911100
OS File Access Attempt Rule ID: 930120
Remote Command Execution: Unix Command Injection Rule ID: 932105
Remote Command Execution: Windows Command Injection Rule ID: 932115
Remote Command Execution: Unix Shell Expression Found Rule ID: 932130
```

### Questions
- Is it something interesting to be added to the CRS exclusions list?
- When you write an exclusion rule set, do you test it on PL1? and if yes, what happens for the higher PL?
- When the exclusion should include HTTP methods not allowed by default on CRS (PUT, DELETE, etc...), could be ok to remove the `911100` (Method is not allowed) by using `ctl:removeRuleById`? Is there something better?
- When there's a free text parameter that could contains everything (including a technical article, that it means code, functions, etc...) and could fires everything on the rule set, how do you usually handle it?

Thanks

**Comment by spartantri** [comment]
Hi @theMiddleBlue,
- I think it could be interesting. I don't know if ghost itself is very popular or not but the exceptions for this kind of application can be used as a template to create other applications exceptions.
- Ideally, you would test the PL that make sense for the app, PL1 is mandatory, often the effort to go PL2 is minimal, however for apps like this one that may contain lots of non-alphanumeric characters PL3 and higher will be hard, but if you use the JSON body processor when JSON content is received most of the special characters go away.
- Removing 911100 may not be ideal, but is ok if you do a  URI and method validation before removing it.
- Free text is really problematic, even more, if you have non-English clients, e.g. french uses lots of apostrophes and characters out of the range chr(192-251) so character enforcing is not possible above PL2, some clients may also encodings for other special characters not supported in ASCII, like Cyrillic and those may cause problems since PL1. In foreign languages, you may not enforce character sets but SQL injection and XSS would have low false positives, this behavior is opposite in English.

For free text stuff you may try adding a PL1 rule to whitelist that ARG as needed, just check size limits and if the posts are using JSON then enforce the body processor for that URI.
```
SecRule REQUEST_URI "@rx /ghost/api/v2/admin/posts/[a-f0-9]{32}/" "id:XXXXXX,phase:1,t:lowercase,noauditlog,chain"
   SecRule REQUEST_METHOD "PUT" "chain,ctl:requestBodyProcessor=JSON"
      SecRule &ARGS:opentext "@eq 1" "ctl:ruleRemoveTargetByTag='paranoia-level/3';ARGS:opentext,blah,blah,blah"
```
Cheers!
