### ISSUE TITLE
Missing Docker base image

### ISSUE THREAD

**Issue by chrira** [SpiderLabs/owasp-modsecurity-crs#1344]
## Type of Issue
Docker build problem

## Description
The base image of the Dockerfile does not exist:
owasp/modsecurity:v2-ubuntu-apache

I don't know the GitHub repo for the owasp/modsecurity Docker image. Therefore I added the issue to this repo.

## Confirmation

[x] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by franbuehler** [comment]
Hi @chrira,
Thanks for this issue.
@csanders is working on this problem. He removed the connected GitHub repo from DockerHub and is now not able to add it because of missing permissions. 
@csanders, what's the status?

The repo for the ModSecurity images can be found at https://github.com/CRS-support/modsecurity-docker.

**Comment by fgsch** [comment]
As @franbuehler pointed out the Dockerfile to build the image is available in the repo above.
For the tests in this repo we have temporarily switched to the latest tag so there is no other action on this ticket.
