### ISSUE TITLE
SQL inject false negative - filter bypass

### ISSUE THREAD

**Issue by chladic** [SpiderLabs/owasp-modsecurity-crs#1398]
I'd like to report false negative for this SQL injection in URL.
Its passing our modsec rules even if we removed all exceptions in place.

https://mydomain.com/sign-in%20or%20(1,2)=(select*from(select%20name_const(CHAR(72,118,86,115,107,102,97,77,100,99),1),name_const(CHAR(72,118,86,115,107,102,97,77,100,99),1))a)%20--%20and%201%3D1

https://mydomain.com/sign-in999999.1%20union%20select%20unhex(hex(version()))%20--%20and%201%3D1

Nothing in modsec_audit log, it pass to application servers without any warning or error.

## Environment
* CRS version 3.1.0:
* ModSecurity-nginx version 1.0.0
* nginx plus R18 (1.15.10)
* Alpine Linux 3.9

**Comment by franbuehler** [comment]
Comment by Walter:

I think 1389 is a more commonly seen issue. It’s because we don’t scan `REQUEST_FILENAME` for sql so heavily. That might be because of FP. If we add that, we might get some FPs. For instance a blog post with `-having-` in the slug is likely to trigger libinjection. So maybe we should do it but in PL2.  

I think a sibling for 942100 on REQUEST_FILENAME would likely be of most value.

**Comment by chladic** [comment]
@franbuehler many thanks for your answer. In this case we will test rule 942100 on REQUEST_FILENAME as you suggested.

**Comment by chladic** [comment]
I added `REQUEST_FILENAME` to rule 942100 like this but it is still not detecting it

`SecRule REQUEST_FILENAME|REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|REQUEST_HEADERS:User-Agent|REQUEST_HEADERS:Referer|ARGS_NAMES|ARGS|XML:/* "@detectSQLi" \`
`"id:942100,\`
