### ISSUE TITLE
Syntax error on line 38 of [...PATH ...]/activated_rules/modsecurity_crs_42_comment_spam.conf: ModSecurity: No action id present within the rule

### ISSUE THREAD

**Issue by rcbarnett** [SpiderLabs/owasp-modsecurity-crs#141]
CORERULES-88: Dled SpiderLabs-owasp-modsecurity-crs-v2.2.5-18-g92c65eb.tar.gz and followed INSTALL file direction and during Apache2.2 configtest:

Syntax error on line 38 of [... MY PATH ...]/activated_rules/modsecurity_crs_42_comment_spam.conf:
ModSecurity: No action id present within the rule

Tkx!

**Comment by csanders-git** [comment]
Reading through this file (modsecurity_crs_42_comment_spam) it appears that this issue was fixed and never closed as there are rule id's for each rule and it loads fine in current ModSecurity 2.9.1. This file was deprecated for CRS v3 in either event. If you think you are having this problem or a similar one please open a new issue and reference this one. Thank you.
