### ISSUE TITLE
941 XSS stopping TinyMCE editor from saving image locations (false positive)

### ISSUE THREAD

**Issue by modernwebsites** [SpiderLabs/owasp-modsecurity-crs#1633]
## Type of Issue

941 XSS stopping TinyMCE editor from saving image file locations or any text containing ../ (false positive)

## Description

Hi. Starting today, I am no longer able to save the output of TinyMCE Rich text editor via post variables. This is specifically when images have been added or the text contains a ../

I found the issue was with REQUEST-941-APPLICATION-ATTACK-XSS as it works OK again when I switch off this rule set. I haven't been able to find out anything online and sorry if I'm missing something obvious but any help would be greatly appreciated. I understand that this is to avoid path traversal, but geat if I can switch the rule group on again and still be able to run the admin CMS which relies on images within content areas. 

## Your Environment

I'm running Centos 6.1 with WHM/cPanel. OWASP Modsecurity 3.0. PHP 7.3.
Apache/2.4.41 

## Confirmation

[YES ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

**Comment by csanders-git** [comment]
This is prevented due to directory traversal attacks. In general, editors (esp those that accept HTML) will always cause a problem for CRS as there is no context to know what is supposed to be allowed and what is an attack. However, it is quite straight forward to whitelist that parameter. 

The CRS team has provided a number of examples in [RESPONSE-999-exclusions](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf.example) and you can also see a good example of how to turn off a given rule for a parameter in the [reference manual](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual-(v2.x)#secruleupdatetargetbyid).

Do let me know if there are any other issues. Thanks
