### ISSUE TITLE
Move tx.allowed_request_content_type list to separate file?

### ISSUE THREAD

**Issue by NullIsNot0** [SpiderLabs/owasp-modsecurity-crs#1651]
It's not a feature request, but more likely a discussion.
Today I put instant messaging platform behind CRS and noticed - when people upload files, rule ID:920420 gets triggered: "Request content type is not allowed by policy". It's because upload is made using POST method and setting Content-Type depending on file type. If image is uploaded, then we get `Content-Type: image/png` or `Content-Type: image/jpeg`, if zip file is uplaoded, then `Content-Type: application/zip`.
I tried to put these allowed content types in [crs-setup.conf](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.3/dev/crs-setup.conf.example#L396:L402), but realised that list can get quite long.
Maybe we can create a .data file with accepted mime types like it's done with php functions in `rules/php-function-names-933150.data`. Will this be useful? Not everyone would consider for example `application/sql` as safe post to application. Maybe it's easier to disable this rule for certain application locations?
[Some MIME types from MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types)
[Complete list of MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml)

**Comment by dune73** [comment]
He @NullIsNot0, thank you for your suggestion. I see your need and I felt the same, but it is a special use case, I'm afraid and it would make things more complicated for everyone else (since we do not have the
concept of configurable datasets in conf files. We do have that for rules with items like security scanner user-agents, but users are not supposed / expected to edit them.

I thought about this before and get the feeling the best would be a replacement for the crs-setup.conf rule that defines this. So _you_ could just rewrite that rule and have it point to a file of your choice. However, I have not found a mechanism to take all entries from a \@pmf and write them into a ModSec variable. (If you find a mechanism, please shout).
 
So I guess the best you can do is to write that file and then generate a rule out of it via script, write that rule into a rule file and source that rule file from withing crs-setup.conf.

Something like this pseudo-bash:

```
cat src | xargs | sed -e "s/^/SecAction /" -e "..." > allowed_content_types.conf
```

I'm closing this for the time being. If you disagree, then please re-open.
