### ISSUE TITLE
Wordpress Problem

### ISSUE THREAD

**Issue by kakigorimochi** [SpiderLabs/owasp-modsecurity-crs#1686]
### Description

I am not sure what will I include here from inside the log file.

### Audit Logs / Triggered Rule Numbers

I am hosting few Wordpress staging sites. And I having problems with the PHP Applications' functionally as a whole. Everything seems to work fine with ModSec turned off. But when it is turned some scripts like file upload are being blocked "wp-admin/admin-ajax.php".

Please help. I have tried looking for a fix for this on google and I can't find anything related to my problem. 

I want to practice server security that's why I try to implement Mod Security on my Personal VPS Server. P.S. SecRuleRemoveById phpids-xx doesn't work.

### Your Environment

* CRS version (e.g., v3.2.0): 3.2.0
* Paranoia level setting: Recommended
* ModSecurity version (e.g., 2.9.3): 3.0.3
* Web Server and version (e.g., apache 2.4.41): Nginx Latest
* Operating System and version: CentOS 7

### Confirmation

[ ] I have removed any personal data (email addresses, IP addresses,
    passwords, domain names) from any logs posted.

N/A

**Comment by dune73** [comment]
Sorry for the inconvenience. Running ModSec / CRS on NGINX can be quite painful. Are you familiar with my tutorials on netnea.com?

Other than that, I am not sure you use SecRuleRemoveById correctly. It's meant to work with numeric ids. Correct?

And then it's likely it stops working because of false positives. Did you enable the WordPress rule exclusion package (see crs-setup.conf file). But even if that is enabled, it's likely you will face more false positives. You need to familiarize yourself with the logfiles available, namely the alerts in the error log.

Hope this helps.

I am closing this issue, as we mean github to be about bugs / problems with CRS, not ModSecurity or NGINX in general.

If you need more help, I suggest you turn to the ModSecurity mailinglist or join us on our slack owasp.slack.com, channel coreruleset.
