### ISSUE TITLE
Unknown warning

### ISSUE THREAD

**Issue by zoltan-fedor** [SpiderLabs/owasp-modsecurity-crs#200]
Hi,
I'm occasionally seeing warnings with no message or explanation what is the warning for.
I haven't added any rules which would trigger this, so it must be some of the base rules.
Anybody has any idea why these might be showing up?
Thanks

--a8e99305-A--
[27/Oct/2014:16:14:36 +0100] VE5hXFFfkaMAAFTKBL4AAAAS 176.63.xx.xxx 51150 81.95.xx.xx 443
--a8e99305-B--
POST /framework-v/php/playback.php HTTP/1.1
User-Agent: UnityPlayer/4.5.4f1 (http://unity3d.com)
Host: test.xxxx.com
Accept: _/_
Accept-Encoding: identity
Content-Length: 20
Content-Type: application/x-www-form-urlencoded
X-Unity-Version: 4.5.4f1

--a8e99305-C--
invitations_id=30601
--a8e99305-E--

--a8e99305-F--
HTTP/1.1 200 OK

--a8e99305-H--
Apache-Handler: fcgid-script
Stopwatch: 1414422876349451 493286 (- - -)
Stopwatch2: 1414422876349451 493286; combined=1556, p1=383, p2=1030, p3=3, p4=102, p5=37, sr=105, sw=1, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.8.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.2.15 (CentOS)
Engine-Mode: "ENABLED"

--a8e99305-Z--

**Comment by dune73** [comment]
This is a very old report. Sorry for taking so long, but I only joined this project long after the issue was submitted.

I have recreate the request as

```
curl http://localhost/framework-v/php/playback.php -d "invitations_id=30601"
```

and it does not trigger the auditlog (nor an alert, but that was never claimed).

I think there might be some sort of ModSec misconfiguration in place (even if you state that you only see these occasionally).  Or it is a ModSecurity bug. I can not see the CRS triggering an auditlog without triggering a rule alert. That would be very odd.

But whatever the reason, I am closing this for now. If you have more infos, then please reopen.
