### ISSUE TITLE
Problems with Rule "960010"

### ISSUE THREAD

**Issue by pfeiffebe** [SpiderLabs/owasp-modsecurity-crs#208]
--379dc719-B--
POST /mail/...../iNotes/Proxy/?EditDocument&Form=s_GetFolderUnreadCountJSON HTTP/1.1
.......

--379dc719-F--
HTTP/1.1 403 Forbidden
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Length: 240
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Content-Type: text/html; charset=iso-8859-1

--379dc719-H--
Message: Access denied with code 403 (phase 1). Match of "rx ^%{tx.allowed_request_content_type}$" against "TX:0" required. [file "/products/apache_jspi/conf/modsecurity-crs/base_rules/modsecurity_crs_30_http_policy.conf"] [line "64"] [id "960010"] [rev "2"] [msg "Request content type is not allowed by policy"] [data "text/plain"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/POLICY/ENCODING_NOT_ALLOWED"] [tag "WASCTC/WASC-20"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/EE2"] [tag "PCI/12.1"]
Action: Intercepted (phase 1)
Stopwatch: 1425280399318434 28338 (- - -)
Stopwatch2: 1425280399318434 28338; combined=303, p1=260, p2=0, p3=0, p4=0, p5=42, sr=37, sw=1, l=0, gc=0
Producer: ModSecurity for Apache/2.9.0 (http://www.modsecurity.org/); OWASP_CRS/2.2.9.
Server: Apache/2.4.12 (Unix) OpenSSL/1.0.2 mod_jk/1.2.40
Engine-Mode: "ENABLED"

I tried first this:
# SecRule REQUEST_HEADERS:Content-Type "^text/plain(.*)" "id:'10000103',phase:1,t:none,nolog,pass,ctl:ruleRemoveById=960010"

but it doesn't seem to work.

So i tried this:
SecRuleUpdateTargetById 960010 !REQUEST_HEADERS:Content-Type:'/^text/plain/'

But i doesn't work also...

Any other ideas?

Greets

**Comment by shrv** [comment]
Good afternoon.
I would have to start the logging for this rule (in step debugging)
And look whether match condition or not. To understand that not work out, the mechanism of CTL or regexp

**Comment by csanders-git** [comment]
I noted that you have a hashmark before this rule, that would comment it out. I would also. Try making sure that the rule fires first then add back the ruleremovebyid. We can try and see why the rule is firing as a false positive if you send us the request that triggers it. In general this approach should work or you might try SecRuleUpdateTargetById. 
#SecRule REQUEST_HEADERS:Content-Type "^text/plain(.*)" "id:'10000103',phase:1,t:none,nolog,pass,ctl:ruleRemoveById=960010"

**Comment by pfeiffebe** [comment]
First of all, thanks for the support =).
I tried this:
SecRuleUpdateActionById 960010 "log,pass"

I know, the rule is know bypassing everything, but it's the only one in the complete ruleset. What do you think about it?

Greets

**Comment by shrv** [comment]
@csanders-git @pfeiffebe 
Good day and good Friday :)

I have one resource for mobile devices. This resource is a problem, the curve request is sent from the client to the server when requesting changes.
The request is no Content-Lenght

Create here is a rule
SecRule REQUEST_LINE "@rx (?i:refresh2)" "phase:1,t:none,pass,nolog,id:'901007',ctl:ruleRemoveById=960012"

But in the logs still see that the rule 960012 to work.
Enable the log on his rule, I see that it also fulfills. It turns out that does not work ctl:ruleRemoveById=960012?

ModSecurity 2.7.7+Apache2.4
Oh, I almost forgot - request is POST

**Comment by dune73** [comment]
The content-type _text/plain_ has been added to the set of allowed content types for Core Rule Set 3.0. So this problem is now gone.

@shrv: Your report is talking of a completely separate topic. On top of it, it is a bit cryptic to me and it is missing important details. If the problem persists with Core Rule Set 3.0, then please open a separate issue.

Closing this now.
