### ISSUE TITLE
non ascii characters causing false positives with different languages

### ISSUE THREAD

**Issue by MichaelHaas** [SpiderLabs/owasp-modsecurity-crs#21]
Rules  981243, 981318 and 981173

The following characters are creating false positives ´’‘ .
I think the best way would be to remove the characters from the rule and add the t:utf8toUnicode,t:urlDecodeUni transformations.
If the removed charcters are needed then they should be moved to another rule so these three rules don't need to be excluded because of false positives. 

Michael

**Comment by nestoru** [comment]
Hi Ryan and all,

It looks like there is a big problem with Unicode. The only way we were able to support unicode across the board is with the below far from ideal removal of several rules.

SecRule REQUEST_URI "@contains /" "phase:1,t:none,pass,id:'14',nolog,ctl:ruleRemoveById=960024,ctl:ruleRemoveById=981318,ctl:ruleRemoveById=981173,ctl:ruleRemoveById=981243"

Would you please provide an update about what version to use that actually corrects the issue? Just sending bunch of Chinese characters to the backend is enough for modsecurity to complain with the rules above one at the time and in that order as we add exclusions.

Thanks!
- Nestor

**Comment by csanders-git** [comment]
@nestoru  could you please provide a list of which rules you've removed to prevent the issue... this is a known issue with how modsecurity uses PCRE.

**Comment by nestoru** [comment]
@csanders-git look into the SecRuleI posted above for the ids of all rules I had to remove. For what is worth I am using Ubuntu 14.04 and this plain old bash recipe https://raw.githubusercontent.com/nestoru/pob-recipes/master/common/apache/mod-security-install.sh

**Comment by tigerxml** [comment]
For these who need to use it (extended solution):
As mentoned above you need:

1) Download unicode.mapping (if you don't have one) https://github.com/SpiderLabs/ModSecurity/blob/master/unicode.mapping

2) 
Add SecUnicodeMapFile /path/to/unicode.mapping
And 
Add SecUnicodeCodePage 20127 (choose number from mapping file) 
or if this is deprecated - use
And Add SecUnicodeMapFile /path/to/unicode.mapping 20127

3) Check if you have t:urlDecodeUni in your rules function (for example open rule you are triggering and check if it there) (if you don't have it - use "t:utf8toUnicode,t:urlDecodeUni" instead of "t:utf8toUnicode" on the next step

4) add SecRuleUpdateActionById 981243 "t:utf8toUnicode"  to the last file in activated_rules  (for example /activated_rules/modsecurity_crs_61_customrules.conf)  (check if /activated_rules/*.conf included into your mod_security config file) (instead of 981243 use your rule number where false positive triggers, or rule ids mentioned by d-schramm )

Hope this will save some time for someone.

**Comment by punlaw** [comment]
Is it possible to remediate the false positive by reshuffling the sequence of  how the transformation is apply?
Since the non asic character is transformed into unicode when t:utf8toUnicode is applied. 
Then when t:urlDecodeUni is applied all the unicode resulted from non ascii character  can potential be transformed to some symbol where modsecurity would deem to be an attack. i.e " 格|imag|" is first transform to unicode "%u683c|imag|" by t:utf8toUnicode  
Then transform to "%u003c|imag|" by t:urlDecodeUni which in ascii is "<|imag|" . And modsecurity is treating the  "<|imag|"  as an attack. 
What if we let the t:urlDecodeUni go before t:utf8toUnicode, then " 格|imag|"  would be passed as "\xe6\xa0\xbc|imag|" to t:urlDecodeUni  since no unicode exist in the original string 
Then when t:utf8toUnicode is applied to "\xe6\xa0\xbc|imag|"  it would only result in "%u683c|imag|" which can pass through the modsecurity.

**Comment by spartantri** [comment]
Yes and no, changing the transforms will affect how rules process the content and prevent issues with some rules but "%u683c|imag|" is not a very friendly payload at all, it will trigger 920220, dealing with other alphabets is problematic often I have to be more forgiving with those fields containing cyrilic or other non-ascii and multi byte encodings. It may be interesting to use the specific target language characters as whitelist so you allow only let's say 1000 different characters instead of 2 million characters of [utf-8](https://tools.ietf.org/html/rfc3629#section-3) not to tell all other encodings.

`"Access denied with code 403 (phase 2). Invalid URL Encoding: Non-hexadecimal digits used at REQUEST_URI. [file \"/usr/share/modsecurity-crs/rules/REQUEST-920-PROTOCOL-ENFORCEMENT.conf\"] [line \"409\"] [id \"920220\"] [rev \"2\"] [msg \"URL Encoding Abuse Attack Attempt\"] [severity \"WARNING\"] [ver \"OWASP_CRS/3.0.0\"] [maturity \"6\"] [accuracy \"8\"] [tag \"application-multi\"] [tag \"language-multi\"] [tag \"platform-multi\"] [tag \"attack-protocol\"] [tag \"OWASP_CRS/PROTOCOL_VIOLATION/EVASION\"]"`

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
