### ISSUE TITLE
Rule 970901 false positive

### ISSUE THREAD

**Issue by thomac77** [SpiderLabs/owasp-modsecurity-crs#223]
We have an application that is hitting the following rule:
 
SecRule RESPONSE_STATUS "^5\d{2}$" "phase:4,rev:'2',ver:'OWASP_CRS/2.2.6',maturity:'9',accuracy:'9',t:none,capture,ctl:auditLogParts=+E,block,msg:'The application is not available',logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',id:'970901',tag:'WASCTC/WASC-13',tag:'OWASP_TOP_10/A6',tag:'PCI/6.5.6',severity:'3',setvar:'tx.msg=%{rule.msg}',setvar:tx.outbound_anomaly_score=+%{tx.error_anomaly_score},setvar:tx.anomaly_score=+%{tx.error_anomaly_score},setvar:tx.%{rule.id}-AVAILABILITY/APP_NOT_AVAIL-%{matched_var_name}=%{tx.0}"
 
The application is an ajax-enabled web client that is returning a 500 status with an json payload indicating the details of the error.   This rule is causing modSecurity to convert to a 403 error code and remove the json payload.  In this particular case, the 500 status was used because the request failed a time-based business logic rule on the server.  The request itself was valid, and repeating the request at a later time would succeed.
 
Since the rule has an accuracy of 9 and a maturity of 9, this seems to indicate that the rule has few or no reported false-positives.  Doing a google search seems to indicate other users have had this error, and resolved by adding a white-list for this rule.  Is this a true false-positive, or is this an application issue that needs to be resolved by using a different error code?

**Comment by csanders-git** [comment]
Good morning @thomac77 this is technically not a "false positive" the rule is designed to catch HTTP errors because it is assumed that allowing these messages to pass freely constitutes a certain level of Information Leakage as defined by both WASC (WASC-13) and CWE (CWE-200). That being said in some cases, like yours you need this data. In your case you might want to remove that rule (SecRuleRemoveByID) and replace it with something that allowed for the logic your application was designed for... 

for instance SecRule RESPONSE_STATUS "^5\d(?:[0-4]|[6-9])$" ...

This example would only allows 505 errors. Hope this helps
