### ISSUE TITLE
Rule 942140 (981320) is missing word boundaries and leads to lots of false positives

### ISSUE THREAD

**Issue by xformerfhs** [SpiderLabs/owasp-modsecurity-crs#248]
Rule 981320 is missing word boundaries and finds the reserved db name "MSDB" in a very, very long base 64 encoded parameter which contains "...zakqbNDy6paKRiugz54XMSDBDfiRE8QwbnmTtjI/Q...". Obviously this is wrong and adding appropriate word boundary handling would make it work correctly.

CRS version is 2.2.9.

**Comment by gazbarg** [comment]
Same problem with cookies which, when random and long, may contain the four characters `msdb` and trigger the rule. Adding word boundaries would solve the FPs.

**Comment by lifeforms** [comment]
Although CRS 2.x is going into legacy mode, this rule is still present in CRS 3.0.0 as rule 942140.

While I'm not the biggest SQLi hacker, I don't see a problem with prepending `\b` to the start of the regexp.

Appending `\b` to the end of the regexp would create a special case however. The reason is that we have the regexp part `d(?:atabas|b_nam)e\W*\(` which matches a string like `db_name(` or `database (`. This regexp part ends with a non-word character `(`, so we can't trivially add `\b` behind it -- there's only going to be a word boundary if the `(` is followed by a word character.

So, to add word boundaries (which I think we should have), we should split this part off from the rest of the regexp.

**Comment by dune73** [comment]
Sounds good to me.

**Comment by dune73** [comment]
@lifeforms, it seems @csanders-git, who self-assigned this, is buried in over stuff. Would you mind taking this over? It's the last remaining issue without a PR for the RC2.

**Comment by lifeforms** [comment]
@dune73 Sure! I'm a bit full today but I can do it by Tuesday.

**Comment by dune73** [comment]
Terrific! Thanks.

**Comment by csanders-git** [comment]
thanks guys!

**Comment by lifeforms** [comment]
A fix is in #608, please add any comments there. Thanks for the reports!
