### ISSUE TITLE
Turn off modsecurity for specific host.

### ISSUE THREAD

**Issue by mailtoyogeshpatel** [SpiderLabs/owasp-modsecurity-crs#249]
We have 2 application on different domain. First application send request to second application , as of now both application request are filter through modsecurity , how to disable modsecurity  for second application when first application send requests to another application.

In short i want to disable modsceurity for specific host.

**Comment by jambock** [comment]
Are these 2 applications running on the same apache server?
If so,  you could set SecRuleEngine off on the main config and then add
SecRuleEngine on to the vhost config of the first application.

You need to be careful if the 2nd application is public facing,  as
ModSecurity will not be protecting it.

Bruno

**Comment by csanders-git** [comment]
There are <i>many</i> ways to accomplish this. The most common way is to use your webservers <location> elements in order to control where the configuration directives are loaded. As @jambock suggested you may use SecRuleEngine. You may also make a rule 
SecRule Request_URI "@contains bob.com/status" "id:123,ctl:ruleEngine=off"
