### ISSUE TITLE
Requiring the Accept header

### ISSUE THREAD

**Issue by mnot** [SpiderLabs/owasp-modsecurity-crs#265]
Rule BEGIN_ACCEPT_CHECK in base_rules/modsecurity_crs_21_protocol_anomalies.conf:

    These rules will first check to see if an Accept header is present.
    The second check is to see if an Accept header exists but is empty.

The Accept header is *not* required by HTTP, either in RFC2616 or RFC7231. Creating a false positive by requiring it here only forces client vendors to send it; I've seen private reports from non-browser clients having bugs due to this, and there's currently an active discussion among browser vendors about dropping Accept from requests.

**Comment by mnot** [comment]
E.g., see:
  https://github.com/letsencrypt/boulder/issues/1019

**Comment by erenfro** [comment]
Hmmm.. After looking through the RFC's and other various resources, I'm having to agree with this. Why IS Accept not being in the client headers in ModSecurity's standard ruleset anyway? I've only ever seen it cause more trouble than be actually useful. Having to specifically whitelist so many sites just because they don't send it.

Looking into this: When a client does NOT sent the Accept header, then the server can assume that it would accept all types, which sounds reasonable to me.

**Comment by rcbarnett** [comment]
The purpose of this rule was to identify non-browser clients - as all major browsers will send it.  It was never meant to be a rule to block on its own.  This rule can be used to mark clients as non-browser in persistent storage or to increase an anomaly score for a transaction that might push it over a blocking threshold when coupled with other rules.

**Comment by erenfro** [comment]
However it's supposed to be used, it's not being used in that manner that I can see. I have had to specifically whitelist various external monitoring sites just to allow them through because the only rule they tripped over is not having an Accept client header. Pingdom is a primary example of one that doesn't use an Accept header, because they don't care what the response is.

**Comment by mnot** [comment]
Even as a heuristic to separate browsers from non-browsers, it's not doing a great job; the browsers want to remove Accept where possible (because it exposes fingerprinting surface area), and non-browsers are  starting to add Accept (for various use cases, including as a workaround for this bug).

**Comment by erenfro** [comment]
@mnot 
Perhaps you could provide some references to the case where browsers are suggesting to remove the header? That might be invaluable in this situation specifically.

**Comment by mnot** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=572650
https://bugzilla.mozilla.org/show_bug.cgi?id=1217933

**Comment by csanders-git** [comment]
The requirement of the accept header is being moved to a higher paranoid level this should take care of this problem in crs 3.0
