### ISSUE TITLE
Require Content-Length to be provided with every POST request

### ISSUE THREAD

**Issue by mnot** [SpiderLabs/owasp-modsecurity-crs#267]
In base_rules/modsecurity_crs_20_protocol_violations.conf:

> This chained rule checks if the request method is POST, if so, it checks that a Content-Length header is also present.

HTTP doesn't require that POST requests have a Content-Length; it's perfectly acceptable to use chunked encoding. If the server needs the Content-Length, it can already reject the request with 411 (Length Required).

While it might be reasonable to say that this is a heuristic for detecting attackers, it is *not* a protocol violation.

**Comment by FlatKey** [comment]
As defined in [rfc2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4):
> For compatibility with HTTP/1.0 applications, HTTP/1.1 requests containing a message-body MUST include a valid Content-Length header field unless the server is known to be HTTP/1.1 compliant. If a request contains a message-body and a Content-Length is not given, the server SHOULD respond with 400 (bad request) if it cannot determine the length of the message, or with 411 (length required) if it wishes to insist on receiving a valid Content-Length.

In my opinion it is a valid rule for a protocol violation. I think these rules are most reasonable in collaborative detection mode, so this rule takes only the weight of a notice. Otherwise feel free to disable a rule you don't need.

**Comment by mnot** [comment]
The specification clearly allows clients to omit Content-Length in some circumstances. It's reasonable to enforce this requirement IF the server is indeed a HTTP/1.0 server, but you can't call it a protocol violation if the protocol isn't being violated.

P.S. RFC2616 is obsolete. Please see RFC723x - http://httpwg.github.io/specs/

**Comment by FlatKey** [comment]
Thank you for update. If an additional check for a missing Transfer-Encoding header would be added, this rule could take place in modsecurity_crs_21_protocol_anomalies.conf

**Comment by mnot** [comment]
That would make sense for HTTP/1.1. HTTP/2 won't have a Transfer-Encoding header either though (although it very often will have a Content-Length header).

**Comment by FlatKey** [comment]
Ok, my proposal:
- the rule 960012 gets a check for request protocol HTTP/1.0 (here it seems to be a protocol violation)
- the same rule take place in modsecurity_crs_21_protocol_anomalies.conf with a new rule id and a check for request protocol HTTP/1.1 and a missing Transfer-Encoding header

What do you think, is that ok?

**Comment by csanders-git** [comment]
If the issue is simply one of switching between protocol violation versus protocol anomaly, we may simply switch this rule without much consequence.

**Comment by mnot** [comment]
@FlatKey LGTM.

**Comment by csanders-git** [comment]
Alright if everyone agrees that this approach makes sense, I think the overhead is minimal enough such that we should merge the pull. Before I do that since i'll have to test it in any event what are your feelings on where this fits in 3.0.0-dev. 
My thoughts are that we adapt the old rule to that provided via @FlatKey. The old rule is located in REQUEST-20-PROTOCOL-ENFORCEMENT.conf within the 3.x ruleset. Additionally my suggestion is we take the new rule (that is to be added to modsecurity_crs_21_protocol_anomalies in 2.x) and add it to protocol enforcement as well however we put in in pass mode with the following comment.
# This rule is by default set to pass such that it only contributes to anomaly mode, change the action to block (from pass) for more paranoid installs.

Any thoughts? After we figure this little nuance out i'll run the testing and merge the pull along with whatever changes to 3.0 we decide need to be made. Cheers!
