### ISSUE TITLE
FP and bypass for 950018

### ISSUE THREAD

**Issue by std0ut** [SpiderLabs/owasp-modsecurity-crs#269]
950018 (CRS_40) uses the compressWhiteSpace transform, which appears to nullify this section of the regex: [^\x0d\x0a]. Basically, the regex ignores CRLF between ".pdf\b" and "#."

Because of this, if a field allows restricted HTML input, an href link to a pdf followed by any sort of HTML color code, would match this rule. This is the type of field I'd most want to protect, because it might explicitly allow a user to add and href tag. I'm sure there are other scenarios where a false positive would occur.

Additionally, the regex can be bypassed by changing the URL to "https." I don't know the full details of the UPDF XSS attack, but I would assume it works just as well with PDFs hosted on SSL-enabled sites.

Is the compressWhiteSpace transform necessary? If so, would it be possible to chain the rule and add a check that there isn't a CRLF between the pdf extension and the hash?

**Comment by csanders-git** [comment]
So i'm digging WAY back into the archives (which i hope to be able to publish again soon when we move to new servers). Ivan originally published this rule and the associated information. He did a presentation on the topic available here:
http://www.owasp.org/images/7/77/Protecting_Web_Applications_from_Universal_PDF_XSS.ppt

**Comment by csanders-git** [comment]
The Text of the orig article:

<p>The Universal PDF XSS vulnerability was a tipping point for most people involved with web application security. Now we know the Web will never be secure for as long we continue to use the exact same technologies we have in use today.</p>

<p>It so happened that I was swamped with work back in January when the news about the Universal PDF XSS had broken out. I kept my eye on the topic during the initial discovery period but I went back to it a month later to give it the attention it deserves. I discovered that the topic received a tremendous amount of interest initially but that the interest died shortly thereafter. The vulnerability was old news in February although there was much more to say.</p>

<p>My presentation, <i><a href="http://www.owasp.org/images/7/77/Protecting_Web_Applications_from_Universal_PDF_XSS.ppt">Protecting Web Applications from Universal PDF XSS</a></i>, aims to be the one place where you can learn everything you need to know about this problem. It also points to an emerging trend of collaborative vulnerability research and briefly discusses its advantages and disadvantages. (As a sidenote, I find the trend very exciting and will probably revisit the topic here again.)</p>

<p>My presentation, <i><a href="http://www.owasp.org/images/7/77/Protecting_Web_Applications_from_Universal_PDF_XSS.ppt">Protecting Web Applications from Universal PDF XSS</a></i>, aims to be the one place where you can learn everything you need to know about this problem. It also points to an emerging trend of collaborative vulnerability research and briefly discusses its advantages and disadvantages. (As a sidenote, I find the trend very exciting and will probably revisit the topic here again.)</p>

<p>I gave the presentation at the OWASP conference in Milan in May but it has been updated since (so don't download it from the conference agenda page). You can download the latest version on the OWASP web site, from the <a href="http://www.owasp.org/index.php/Universal_PDF_XSS">web page dedicated to the problem</a>. I will be giving the same talk later this month (June 22) for the <a href="http://www.owasp.org/index.php/Belgium">OWASP Belgium-Luxemburg chapter</a>.</p>

<div id="a000127more"><div id="more">

</div></div>

<p class="posted">Posted by <font size=3><b>ivanr</b></font> at June 12, 2007 02:23 PM</p>

**Comment by csanders-git** [comment]
My thoughts are that you are right ... using compresswhitespace here is probably a poor idea (however we run into issue with lots of whitespace, in the future we should split out compress whitespace and remove line feeding maybe?. In general i'm not sure about the https bit too but it probably couldn't hurt. I think making these changes will make the rule functional again. Don't think we can do much about the whitespace issue right now.... i'll have to investigate if the CRLF is really necessary.

**Comment by std0ut** [comment]
This probably isn't optimized regex, but this might be one way to potentially compress white space, but still exclude CRLF (don't compressWhiteSpace in second rule):

SecRule ... "http:\/\/[\w\.]+?\/.*?\.pdf\b.*?#" "chain,t:lowercase,t:compressWhiteSpace,.."
SecRule ... "http:\/\/[\w\.]+?\/.*?\.pdf\b[^\x0d\x0a]*#" "t:none,t:lowercase,..."

**Comment by dune73** [comment]
@csanders-git Has this been adressed, or do we need to act?

**Comment by dune73** [comment]
This rule has been removed from the CRS3 a long time ago. So the FP problem solved itself.

If you guys think we still need to address this attack vector, then please open a new issue. Closing this now.
