### ISSUE TITLE
false positive drwxr?

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [SpiderLabs/owasp-modsecurity-crs#270]
base_rules/modsecurity_crs_45_trojans.conf
Line 34
```
SecRule RESPONSE_BODY "(?:<title>[^<]*?(?:\b(?:(?:c(?:ehennemden|gi-telnet)|gamma web shell)\b|imhabirligi phpftp)|(?:r(?:emote explorer|57shell)|aventis klasvayv|zehir)\b|\.::(?:news remote php shell injection::\.| rhtools\b)|ph(?:p(?:(?: commander|-terminal)\b|remoteview)|vayv)|myshell)|\b(?:(?:(?:microsoft windows\b.{0,10}?\bversion\b.{0,20}?\(c\) copyright 1985-.{0,10}?\bmicrosoft corp|ntdaddy v1\.9 - obzerve \| fux0r inc)\.|(?:www\.sanalteror\.org - indexer and read|haxplor)er|php(?:konsole| shell)|c99shell)\b|aventgrup\.<br>|drwxr))" \
```

What good does drwxr do here other than censoring the word drwxr in the response body? If I wrte a comment "I hate drwxr" then that page gets blocked?

**Comment by csanders-git** [comment]
Most of these are linked to historically used webshells... I will admit however that drwxr seems overly broad.  The logic behind it is fairly clear in order to block permissions of file listings, which web shells will typically show, but i do think it is a tad vague. I am not sure if we think it is worth it to keep this logic but expand it to look for full file permissions regex's or not. thoughts?

**Comment by asdfljdasflkjwfd** [comment]
How hard is it for the webshell to format permission with numbers or some other format? Imo this approach is very ineffective.

**Comment by csanders-git** [comment]
I'd agree that the approach presented here can be easily bypassed ... the point is not that this is true, because it is also equally trivial to change the title of a given webshell. I think the original idea here is that we don't normally display file permissions on a page (not sure if i agree with this btw) and so pages that do display such things should have exceptions added.
Another important fact is the idea that just because people can deploy another mechanism doesn't mean this won't stop those too lazy to do so. It turns out that simple defense mechanisms like this tend to be fairly effect (although maybe not the drwxr aspect of this rule).
For evidence of a simple technique that simply requires attackers to be less lazy i'll put forth something like the cloudflare anti-ddos stuff (https://khromov.wordpress.com/2013/02/05/cloudflare-client-side-ddos-detection-how-does-it-work/). An attacker can simply bypass this by adding javascript, many won't and therefore its effective. 

That was my reasoning behind keeping a format permission check still in there but I do like your logic and am open to taking it out. Any other thoughts from you or others?

**Comment by ktwombley** [comment]
The signature on "drwxr" makes it nearly impossible to post a transcript of a shell session to a blog hosted on a mod_security website. I don't know how common it is, but it happened to me, which is how I found this bug. :)

**Comment by csanders-git** [comment]
hmm this is a good point. perhaps this is worth an email to the mailing list to determine if we think it is enough to force people to add exceptions or to remove it entirely. I assume both of you @ktwombley  and @asdfljdasflkjwfd  think we should remove it entirely?

**Comment by ktwombley** [comment]
I see three aspects here:
* Low probability of True-Positive; In order for "drwxr" to match traffic which would not otherwise be matched, the web shell would have to have no other pattern matches, and the web shell user would have to execute "ls -l" (or some other equivalent) during their session.
* High probability of False-Positive; it will match on traffic which contains "drwxr", such as how-to articles or demonstrations including transcripts of shell activity.
* Ease of bypass; While this applies to the rest of the strings in the pattern as well, it is pretty easy to bypass the search for just "drwxr" with evasion techniques. If a web shell author were to attempt to evade all of the other strings we search for, they will also easily evade the check for "drwxr" as well.

Because of all of those, yes, I am in favor of dropping "drwxr"

**Comment by csanders-git** [comment]
pretty much everyone i've spoken to has shared this opinion, as a result I am going to push a change (when i get a few seconds free) that removes this aspect of the rule.

**Comment by asdfljdasflkjwfd** [comment]
I agree with this change. Some hosting providers have this rule enabled by default globally and do not want to make changes to the config themselves.

**Comment by zinoe** [comment]
As it seems, this rule will not be used in release 3.0.0-rc1 anymore. Therefore, this issue is potentially obsolete.

**Comment by dune73** [comment]
Depends, if the 2.2.X branch gets another release. If it gets another release,then dropping drwxr from the regex seems like the smallest problem we have with 2.2.X. ;)

**Comment by csanders-git** [comment]
@dune73 I can update 2.2.x to reflect this change tonight :)

**Comment by zinoe** [comment]
Since this is still open, I will create a PR closing this issue.

**Comment by dune73** [comment]
Fix has been merged. I'm closing this.
