### ISSUE TITLE
MULTIPART_UNMATCHED_BOUNDARY how to debug the cause

### ISSUE THREAD

**Issue by divitoDBA** [SpiderLabs/owasp-modsecurity-crs#279]
Hi, I'd like to confirm the cause for this issue. I've reviewed a lot of pages, even this repository, but I was unable to find out a method that help me to debug it properly. Most of recommendations are just to disable rule "200003".

I've collected both payload and modsecurity debug files. How can I debug it properly ?

i will appreciate your guidance.

Regards

**Comment by dune73** [comment]
RuleId 200003 is a beast (and it's not part of the core rules). Personally, I do not use it on production sites due to the high number of false positives.

If you want to debug it, try to find the unmatched boundary by hand. If it is not obvious, reduce the size of the file and submit it again and again until you have identified the passage, which triggers the alert.
