### ISSUE TITLE
Handling mod security as a firewall for all kind of web sites

### ISSUE THREAD

**Issue by avifatal** [SpiderLabs/owasp-modsecurity-crs#297]
Hi,
We are 200 of websites / webapps for our clients.
From wordpress to .net apps, java and more.

We want to provide a united waf solution for all of them.
going to cloud will be very expensive.

 I have built for this an Apache proxy with mod security and owasp rules. the mod security is not blocking, just logging.
I took 10 websites and and pass the traffic via this proxy.
after 5 minutes I opened the log and saw 150 different types of security issues.

Its more of a conceptual question... 
How can I manage a solution for 200 of webapps? does it makes sense? 
I can understand controlling on five websites, but 200 ? its sounds like 24 hours we need to go over rules and suspend them on every usecase....

Ill be glad to hear from people who has an experience with that.

Thanks

**Comment by dune73** [comment]
@avifatal: This is a conceptual topic and a question with regards to the best methodology to integrate the core rules in a big setup. Github issues are meant to look at bugs in the rules. So this is probably the wrong place to discuss this.
However, your problem is very real and also very typical. May I invite you to ask the question on the core-rules mailinglist (-> https://lists.owasp.org/listinfo/owasp-modsecurity-core-rule-set)? I would be happy to give you a few hints and pointers.

**Comment by csanders-git** [comment]
@avifatal if you don't wanna ask on the mailing list I can answer here in a little detail but @dune73  brings up a good point, you'll get far more feedback on the mailing list from people in the same situation as you are currently in. For now i will close this topic, if you need it answered here please just respond :) thanks for reaching out

**Comment by avifatal** [comment]
Done. thanks
