### ISSUE TITLE
Review exclusion documentation

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#319]
The file `REQUEST-00-LOCAL-WHITELIST.conf.example` is rather short. It should contain various examples of common whitelist rules. Some ideas:

Whitelist a cookie from all CRS rules after validating it (should be recommended- this only skips when the value is known to be safe):

```
SecRule REQUEST_COOKIES:PHPSESSID "^[a-zA-z0-9\-,]+$" \
    "id:1,phase:request,t:none,nolog,pass,\
        ctl:ruleRemoveTargetByTag=CRS;REQUEST_COOKIES:PHPSESSID"
```

Whitelist a get/post parameter from all CRS rules

```
SecRule REQUEST_FILENAME "@endsWith /wp-login.php" \
    "id:2,phase:request,t:none,nolog,pass,\
		ctl:ruleRemoveTargetByTag=CRS;ARGS:pwd"
```

Whitelist all get/post parameters from CRS rules

```
SecRule REQUEST_FILENAME "@endsWith /weirdform.php" \
    "id:3,phase:request,t:none,nolog,pass,\
		ctl:ruleRemoveTargetByTag=CRS;ARGS"
```

Whitelist a url completely from CRS rules (should be discouraged)

```
SecRule REQUEST_FILENAME "@endsWith /weirdform.php" \
    "id:4,phase:request,t:none,nolog,pass,\
		ctl:ruleRemoveByTag=CRS"
```

Disable all rules for a platform or language not in use, e.g. `platform-windows`:

```
SecRule REQUEST_FILENAME "@endsWith /weirdform.php" \
    "id:5,phase:request,t:none,nolog,pass,\
		ctl:ruleRemoveByTag=platform-windows"
```

Disable all the Windows rules for a complete site/vhost:

```
SecAction \
    "id:6,phase:request,t:none,nolog,pass,\
		ctl:ruleRemoveByTag=platform-windows"
```

Explain to create a new .conf file with the same name to make it active (file is now called .conf.example)

Explain that `ctl:ruleRemoveTargetById/Tag` and `ctl:ruleRemoveById/Tag` must be run BEFORE the CRS rules. If the user desires to put these whitelistings in a different .conf file, it must be included in Apache config earlier than the CRS.

Maybe also explain the `SecRuleRemoveByTag/Id` rules. Though these must run AFTER. I don't know if there is any advantage to them. If so, should we explain it? If not, could we settle on recommending just one system instead of two?

**Comment by csanders-git** [comment]
These are great! i'll add these examples now... some of these i never even thought of :-P

**Comment by csanders-git** [comment]
It might be necessary to add the tag OWASP_CRS if we're going to show this example. We could add it as a SecDefaultAction

**Comment by csanders-git** [comment]
I think the platform-IIS example works better as an exception rather than a whitelist. Thoughts?

**Comment by dune73** [comment]
I was never quite sure what the wording with regards to whitelist and exceptions were with the "official" crs documentation. 

I usually use the term "ignore-rule", but I am not sure it's a very good term either. And I reserve "whitelist" for a positive ruleset (something outside the scope of ModSec).

Here is an example out of my teaching material, that allows the alert, but nullifies the scoring. This helps in an anomaly scoring setup where you want to retain the alerts but you do not want to block because of a certain alert. This is an issue, because writing an exception/ignore-rule effectively turns you blind with regards to the said alert and two years down the lane, you are no longer sure it's still an issue.

```
SecRule REQUEST_FILENAME "@beginsWith /app/submit.do" "chain,phase:2,log,pass,t:none,id:10003,msg:'Adjusting inbound anomaly score for rule 950005'"
SecRule "&TX:950005-OWASP_CRS/WEB_ATTACK/FILE_INJECTION-ARGS:contact_form_name" "@ge 1" "setvar:tx.inbound_anomaly_score=-%{tx.critical_anomaly_score}"
```

**Comment by csanders-git** [comment]
hmmm - it would be nice if there was a better name here, I agree. In the past i've termed them differently based on transaction-specific-exceptions versus general exceptions - this seems pretty wordy but it's what i tried to convey in the docs.

**Comment by csanders-git** [comment]
@dune73 I think this needs more discussion. I'd say ignore is not right because it might not really be ignoring (or whitelisting for that matter, it can generally be changing the functioning of a given rule or the engine as a whole (think ctl:requestbodyaccess for instance) 
so what i'm thinking is
 REQUEST-00-LOCAL-TRANSACTIONAL-MODIFICATIONS
 REQUEST-00-LOCAL-TRANSACTIONAL-CHANGES
 REQUEST-00-LOCAL-PER-TRANSACTION-MODIFICATIONS 
 REQUEST-00-LOCAL-PER-TRANSACTINL-CHANGES

something like that? thoughts?

**Comment by dune73** [comment]
I am thinking about this on that 350 pages project I am working on as well.

@csanders-git the distinction between general and request-based you made in March is useful, I think.

Ivan Ristić is strong on the term "transaction", while I do not like it that much (it's a bit too broad in my eyes, but then it's probably better than request which would mean the transaction without the response phases in ModSec context).

So what options do we have right now?
- Transactional changes (and friends)
- Whitelist rules
- Ignore rules
- Exception handling
- False positives rules
- Anti-FP rules
- Bypass rules

Anything else?

Bypass occurred to me today in the shower. It comes with this shortcutting idea, which is also part of the original Whitelist term. Also all the `SecRemoveRuleByXX` style rules bypass some checks.

What do you guys think?

**Comment by csanders-git** [comment]
I think exception handling, false positive, and anti-fp are not great as they don't really discern between the SecRemoveRule* and SecUpdateRule*, since we're calling those exceptions and the rules at the beginning. I'm with you I really don't like 'whitelist' more and more now. I'd love to put something different in this glob of exceptions text i've written for the documentation https://github.com/SpiderLabs/OWASP-CRS-Documentation/blob/master/exceptions.rst 

bypass isn't bad, i think it makes more sense switched but i still like it.
RESEPONSE-99-BYPASSES
REQUEST-00-EXCEPTIONS?

or maybe the 'modified-rules' 

I'm really not in love with an answer yet

**Comment by dune73** [comment]
Let's continue the discussion a bit.

Config time and runtime exceptions/rule circumventions are two distinct techniques. But they serve a common goal: Suppression of false positives (or performance loss). I think using two totally distinct terms is blurring things for the user. There needs to be a link between the terms if you ask me. What if we would call it:
- Config-Time Bypass (-> SecRemoveRule* and friends; or startup time Bypass, unconditional Bypass)
- Runtime Bypass (ctl:ruleRemove* and friends; or context-based Bypasses, conditional Bypass)

I think the unconditional / conditional idea has some potential as it seems this is what sets the two techniques apart.

**Comment by lifeforms** [comment]
'Config-time / runtime' is a great distinction.

For me 'bypass' has a negative connotation. If an attacker evades a rule it's what I call a bypass. Though I also have an audio device which has a bypass button to disable its processing temporarily. So it's okay. 'Writing exceptions' sounds like a good name. I usually talk about 'whitelisting' but will adopt the conventions adopted here!

**Comment by dune73** [comment]
Is config-time and runtime really understandable for users? It's really what happens, but will they understand it without further explanations?

Interesting thoughts on 'bypass'. For me the connotation is positive (heart bypass operation and streets bypassing a city are the most common uses I know. But that's probably a German culture thing. 'Bypass' would be a totally new term, so we really need to think this through. The attacker evading a rule is a related bypass. He bypasses the alert, while we want to bypass the execution
of the rule. But I think this distinction is actually beneficial in the course of a discussion of the problem.

For me exception is something of an alert. An exception happens. It is not written. I doubt people will understand that we mean writing an exception to the usual course of action of the ruleset.

**Comment by csanders-git** [comment]
I do really like the distinction :). How about modification.

config-time-modification (perhaps boot-time-modification, start-time-modifications, startup-time-modifications - config time might not be clear enough)
run-time-modifications

run-time-modifications

**Comment by dune73** [comment]
Is not everything a modification? The terms exception, whitelisting and bypass are all more specific. I think modification is very general.

@lifeforms : Still think bypass has a negative connotation?

**Comment by csanders-git** [comment]
@dune73 thanks for bringing this back up we need to make progress this week on it :)

**Comment by dune73** [comment]
Agreed. :) I'm approaching the chapter in question in that other project of mine...

**Comment by csanders-git** [comment]
So what are the current front runners in your mind?

**Comment by lifeforms** [comment]
@dune73 Yeah... I mean if you google "ModSecurity bypass", you will only see it used as a synonym of evasion. I've never heard it used in the context of an *authorized* alteration of firewall settings. To me it sounds like getting around something that's actually there or should be there. Wikipedia says [Bypass (computing), in computing, circumventing security features in hacking, or taking a different approach to an issue in troubleshooting](https://en.wikipedia.org/wiki/Bypass).

**Comment by lifeforms** [comment]
I've added some more brainfarts to the issue description.

I always wondered why there are two systems - `ctl:ruleRemoveTargetById/Tag` versus `SecRuleRemoveByTag/Id`. I use the `ctl` one in 99% of the situations except for some very early whitepass-anti-FP-exceptions. Is there actually an advantage to the `SecRuleRemoveByTag/Id` directives? If not, should we teach people to use both at all? I always found this terribly confusing as a user (and still do). Especially since their usage is so different (before/after).

**Comment by csanders-git** [comment]
There is a massive advantage to using SecRuleRemoveBy* from a performance perspective as it isn't in memory. It is removed at boot as opposed to being removed per transaction.

**Comment by dune73** [comment]
I like the readability of SecRuleRemoveBy*. I teach to use both and advocate the use SecRuleRemoveBy* for Cookies.

**Comment by dune73** [comment]
I agree. Bypass is ruled out.

Stumbled over some documentation where I call it "Rule exclusions". This leads to "Directive to exclude a rule" and "Rule construct to exclude a certain rule", etc.

Any good?

**Comment by lifeforms** [comment]
@dune73 Yeah!

**Comment by dune73** [comment]
@lifeforms seems to like "Rule exclusions". Let's tally it up against the other options (each one with a usage example)

(1) Whitelisting -> "Whitelisting rule" (conflict with the term "Whitelisting" used as in "Blacklisting")
(2) Transactional changes (and friends) -> "Transactional change to existing rule"
(3) Ignore rules -> "Ignore rule to skip an existing rule"
(4) Exception handling -> "Rule handling an exception caused by a false positive"
(5) False positives rules -> "False positive rule to handle unwanted alerts"
(6) Anti-FP rules -> "An Anti-FP rule to handle unwanted alerts"
(7) Bypass rules -> "A rule to bypass another rule"
(8) Modification rules -> "A rule modifying another rule at runtime"
(9) Rule exclusions -> "Rule construct to exclude a certain rule"
(10) Exclusion rules-> "An exclusion rule to skip a certain rule check"

Most of these are already ruled out for various reasons discussed above in this thread. (9) and (10) may have the edge here as they do not imply something they do not deliver. So I think these terms can be used and defined in a way we choose. But they are not very elegant, I think. This might be acceptable though, as we have been breeding over this question for weeks on end now.

**Comment by csanders-git** [comment]
keep in mind that we also have to distinguish between 00 and 99 rules somehow :-X

**Comment by lifeforms** [comment]
@dune73 will do a limited edit to the files in-place with #493 and we can do a bigger update of the documentation for RC2 if needed.

**Comment by dune73** [comment]
I'm currently working on PR for this. Will take some time though.

**Comment by dune73** [comment]
Closing in favor of PR #601.
