### ISSUE TITLE
Improve potential DoS rule (981049/912100)

### ISSUE THREAD

**Issue by zinoe** [SpiderLabs/owasp-modsecurity-crs#321]
As part of the CRS3 paranoia project, we will be discussing possible [stricter siblings](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode#Stricter_siblings_for_existing_rules) for some rules. The goal of this series of issues is to discuss the exact details.

This issue brings up rule 981049 (2.2.x) / 912100 (3.0.0-rc1). Information on the proposed changes can be found [here](https://www.owasp.org/index.php/OWASP_ModSec_CRS_Paranoia_Mode_Sibling_981049).

Please add your thoughts, proposals or concerns in the comment section.

**Comment by loudly-soft** [comment]
I’m new to ModSecurity but I’m almost certain that the new rule 912100 (3.0.0-rc1) would be overly paranoid by causing false positives because ```ip:dos_burst_counter``` will **also** be set to 1 for steady requests arriving at, say, once every hour, and mistakenly blocked.

The old rule 981049 (2.2.x) works well with the condition ```IP:DOS_BURST_COUNTER "@ge 2"``` because the actual burst detection doesn’t start until ```ip:dos_burst_counter``` has crossed 1.  When that happens, ```ip.dos_burst_counter``` has ```TX.DOS_BURST_TIME_SLICE``` seconds to accumulate ```TX.DOS_COUNTER_THRESHOLD + 1``` number of requests to qualify for a burst and a block.  (The “+ 1” is because rule 981048 uses “gt” operator instead of “ge” even though the rule comment says “greater than or equal to”.) 

The old rule works very well with a few minor caveats.

1. In the worst case, it takes 2 bursts for a new IP never seen before (or forgotten) by ModSecurity before it’s blocked.

2. It has been reported in the OWASP mailing list that the rules trigger false positives for concurrent requests falling well short of the specified burst threshold.

IMHO, I don’t think the delay in *#*1 is a big issue warranting a fix.  As long as the IP is eventually blocked, the delay is insignificant.   Also, *#*1 only happens in the worst case scenario.  If a user had sent ```TX.DOS_COUNTER_THRESHOLD + 1``` requests steadily over time before bursting, he will be blocked right after the first burst.

I can confirm *#*2 because it happened to my own users who are sending concurrent requests even though the number of requests is well below the specified burst threshold.  They were erroneously blocked.  This is actually the reason why I started digging into the anti-DOS rules to devise a fix.

**Comment by dune73** [comment]
Hello @loudly-soft. Thank you for taking the time to look at this in detail. I am addressing them in the conversation on the pull request #335. Please come over as well.

**Comment by csanders-git** [comment]
@loudly-soft that is good feedback I think @dune73's DOS rules which I merged yesterday into the v3.0.0-rc1 branch take account of the timing issue really nicely. Since the updated DOS rules contain the paranoia level 2 rules i'm going to close this thread. If you think that's in error or you have more to say please reopen it. Hopefully you enjoy the new DOS rules :)
