### ISSUE TITLE
Password triggers rule 950901

### ISSUE THREAD

**Issue by michyprima** [SpiderLabs/owasp-modsecurity-crs#332]
See:

ModSecurity: Access denied with code 403 (phase 2). Pattern match "(?i:([\\s'\"`\xc2\xb4\xe2\x80\x99\xe2\x80\x98\\(\\)]*?)\\b([\\d\\w]++)([\\s'\"`\xc2\xb4\xe2\x80\x99\xe2\x80\x98\\(\\)]*?)(?:(?:=|<=>|r?like|sounds\\s+like|regexp)([\\s'\"`\xc2\xb4\xe2\x80\x99\xe2\x80\x98\\(\\)]*?)\\2\\b|(?:!=|<=|>=|<>|<|>|\\^|is\\s+not ..." at ARGS:password. [file "/etc/nginx/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "77"] [id "950901"] [rev "2"] [msg "SQL Injection Attack: SQL Tautology Detected."] [data "Matched Data: dC8^vQgH9JP found within ARGS:password: n@*dC8^vQgH9JP"] [severity "CRITICAL"] [ver "OWASP_CRS/2.2.9"] [maturity "9"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [hostname ""] [uri "/admin/"] [unique_id "AaacAcAcAcOxAcA6rc7cAcAc"]

**Comment by lifeforms** [comment]
First, you might want to change the password that you've posted in the bug report!

Unfortunately this rule ("SQL Injection Attack: SQL Tautology Detected.") is known for many false positives. That's why in version 3 of the CRS, we will move it to a stronger 'paranoia mode' and it won't be used by default.

You got this problem on url `/admin/`, so for now, you can write a whitelisting rule for it. Assuming you are running Apache, you can add the whitelisting to your general config file (so it's whitelisted on all sites) or to a single virtualhost configuration. The whitelisting rule could look like the following:

```
SecRule REQUEST_FILENAME "@streq /admin/" \
    "id:1234567,phase:request,t:none,nolog,pass,\
        ctl:ruleRemoveTargetById=950901;ARGS:password"
```

This will ensure that on files called `/admin/`, the `password` parameter will not be checked for rule 950901.

If you have any questions or problems getting the whitelisting to work, please post to the [modsecurity mailinglist](https://lists.sourceforge.net/lists/listinfo/mod-security-users).

Since the general issue has already been addressed with CRS3 (which is in the works, though not quite final) I'm closing this issue, thanks for the report!
