### ISSUE TITLE
Improve potential SQL injection authentication bypass

### ISSUE THREAD

**Issue by istais** [SpiderLabs/owasp-modsecurity-crs#341]
It may be possible to perform authentication bypass using the following vectors:

```
1 or isAdmin=1
1 or isAdmin like 1 
```

In order to perform the attack, the web application must implement the authentication control using an SQL injection as the following:

select \* from users where username = $_GET['u'] and password = $_GET['p];

and the "users" table must contain a known column name (such as "isManager", "isAdmin", "Admin") with a predictable value (such as "1")

**Comment by dune73** [comment]
Thanks for reporting @istais.

I confirm that neither 2.2.9 nor 3.0.0dev complains about this, not even in a high paranoia level.

Do we want to detect this or is this too stupid an application? As soon as you go "1=1" instead of the isAdmin field, ModSec is complaining swiftly. So maybe this takes so much knowledge on the attacker side, that ModSec has a hard time preventing such a backend-depending exploit.

What do you guys think?

**Comment by csanders-git** [comment]
really I am unsure how we could go about writing a rule for something this without being REALLY too specific or so general as a metric ton of FP

**Comment by dune73** [comment]
Same here. 

But at least libinject should catch it, don't you think? I mean you look at it and it immediately looks like SQL, but the parser does not get the same impression.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
