### ISSUE TITLE
Split off php-variables.data to PL3 rule

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#357]
The use of the ARG_NAMES value within 933130 causes extensive issues with Wordpress due to their parameter names. The suggestion is the make a version with ARGS_NAMES at paranoid level 2.
Is the use of such words common within attacks using register_globals? @lifeforms 
![screenshot from 2016-06-15 15-39-10](https://cloud.githubusercontent.com/assets/4632287/16094678/5556192a-330f-11e6-8484-b1b8f0722438.png)

**Comment by lifeforms** [comment]
@csanders-git Good find. To be honest there's a lot in the `php-variables.data` file that I don't overly care about. About the top half of the data file is interesting from an attacker standpoint (though easy to evade). Starting at `AUTH_TYPE` the data file gets kinda meh. The `PHP_` strings would hopefully not turn up so often in FP though, so they could be nice to keep for now.

We could split off the losers to a higher paranoia level if you like to keep them. Maybe PL3 since they kinda attract FP and are not overly important in my opinion? Just by educated guess I think they'll be a lot worse than many other PL2 rules. But if you guys think it's worth it for PL2, that's fine with me.

To recap I'd propose moving these terms to PL3.

```
AUTH_TYPE
HTTP_ACCEPT
HTTP_ACCEPT_CHARSET
HTTP_ACCEPT_ENCODING
HTTP_ACCEPT_LANGUAGE
HTTP_CONNECTION
HTTP_HOST
HTTP_KEEP_ALIVE
HTTP_REFERER
HTTP_USER_AGENT
HTTP_X_FORWARDED_FOR
ORIG_PATH_INFO
PATH_INFO
PATH_TRANSLATED
QUERY_STRING
REQUEST_URI
```

**Comment by csanders-git** [comment]
I'm inclined to agree with you but perhaps these make more sense while trying to detect code. As you said the FP rate should be low (within parameters). I think it is just the locations that will lead to increased false positives.

**Comment by lifeforms** [comment]
@csanders-git That's true, but stuff also ends up in `ARGS_NAMES` when it's just passed as a query string (e.g. `/foo?PAYLOAD_HERE`), which is effective in a lot of vulnerabilities, so I think checking that variable is pretty much a must for most rules. There's a lot of options, but I would rather start with moving around the less important terms and see how we fare then.

**Comment by csanders-git** [comment]
That sounds pretty reasonable - I can make a PR with the modified files ... is that pk with you?

**Comment by lifeforms** [comment]
@csanders-git Sure!

**Comment by dune73** [comment]
ACK

**Comment by lifeforms** [comment]
Closing this, PR is in #473
