### ISSUE TITLE
Rule 920450 (CRS3): tx_restricted_headers includes "Proxy-Connection"

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#365]
tx.restricted_headers in setup.conf includes "Proxy-Connection" (and has done so in 2.2.X as well). But I am now seeing FPs in production on this header. With the few FPs remaining in CRS3, this is suddenly a substantial source of FPs in my production site. So I think we want to suppress this.

I see that this header might be an abuse target. But I think it is beyond the scope of PL1 (the PL of 920450).

So I see two options:
- Move 920450 to a higher PL (-> 2)
- Remove Proxy-Connection from the restricted_headers list
- Split restricted_headers for different PLs and add a stricter sibling covering the new restricted_headers_high_PL in a higher PL.

Thoughts?

**Comment by lifeforms** [comment]
I see a lot of noise from this header as well. I can't recall security problems with `Proxy-Connection`, so I don't know if it's interesting to log it. Is there actually a problem?

Sending the header seems a very widespread practice. I see thousands of `Proxy-Connection` request headers daily on a big site without HTTPS, so I think there are ISPs doing transparent proxying who add this header. I like being strict about the standards, but if it's violated on a regular basis, the cat's out of the bag and the users will only blame us. So, if there are no concrete server security issues with the header, I propose we remove this header from the default.

Another part of the setting is `Via`. I don't know why this is restricted. It seems to me perfectly normal and acceptable. I see it less often than `Proxy-Connection` but still a lot. [Wikipedia also lists it as a standard request header](https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Request_fields). So, I propose to remove that one from the default too.

If the rule would only act in PL2+, I feel we're making the feature harder to understand.

Since it's a setting anyway, we could set a conservative default, and have the user add data itself, if needed.

So this would be my suggestion:

```
  setvar:'tx.restricted_headers=/Lock-Token/ /Content-Range/ /Translate/ /if/'"```
```

While we're discussing this setting, the `restricted_headers` rule itself is kinda weird anyway. Its rule only logs at WARNING level. So, you get noise in the logs but no action. This is in contrast to the `restricted_extensions` setting, which is defined in the same paragraph of the setup, but which has a rule that acts at *CRITICAL* level. The difference is undocumented as of yet. This also seems hard to understand for a user. If they'd add a restricted header to the setting, I think they'd have the expectation to actually block clients that send it.

Should we change the rule to critical, now that we've removed the FP from it?

**Comment by dune73** [comment]
@lifeforms : I do not think the feature would be harder to understand in PL2 or 3. Restricting certain headers is something advanced in my eyes.

Other than that, I agree with you wholeheartedly. And thanks to the confirmation that this is seen a lot. I think so too. Also in 2.2.X.

But let's hear what @csanders-git has to say.

**Comment by lifeforms** [comment]
@dune73 Well if a user would want to restrict a header, it's weird to me that they'd also have to run in PL2, which comes with a whole lot of other effects and false positives, and even then they would only get warnings and not critical alerts. The rule is just not well designed in my opinion. I think if it behaves the same as restricted_extensions and remains orthogonal to PL it becomes much clearer. If we remove the FP causing defaults we can achieve this IMO.

**Comment by lifeforms** [comment]
(If Proxy-Connection and Via would be useful to log at PL2, we could split the rule and have multiple settings, I agree... And in the same vein we could think of splitting into warn_headers / block_headers... But I don't think it's too interesting, so making extra variables for it is not worth it)

**Comment by dune73** [comment]
No, I do not think this is weird. There is a ton of protection you are only getting in PL2 in the 942* rule range. People will opt for PL2 in order to get higher protection. This would then come with header restrictions.

(The idea that people would want header restrictions and then be surprised at the rest that comes with it seems less likely in my eyes).

However, I agree with you that the use case for header restrictions of `Via` and ^Proxy-Connection` is hard to find and it's not worth the hassle. Rather remove the two headers, raise the severity and let it be.

**Comment by dune73** [comment]
Taking a 2nd look, I get the impression, that the `restricted_extensions` rule (920440) is misconfigured:

```
920450: PL 1: tx.restricted_headers : block : severity:WARNING : warning_anomaly_score
920440: PL 2: tx.restricted_extensions : block : severity:CRITICAL : warning_anomaly_score
```

Severity and anomaly score level are clearly misaligned. I think the idea of the filename extension restriction has always been a critical anomaly score. It's just that nobody noticed or cared to submit an issue.

I suggest a PR which takes @lifeforms' proposed header list and re-configures rules as follows:

```
920450: PL 1: tx.restricted_headers : block : severity:CRITICAL : critical_anomaly_score
920440: PL 2: tx.restricted_extensions : block : severity:CRITICAL : critical_anomaly_score
```

Any objections to this course of action?

**Comment by csanders-git** [comment]
Seems like there aren't any objects -- this is actually a great catch

**Comment by dune73** [comment]
Thank you guys. Been busy all week. But will do the PR now.
