### ISSUE TITLE
Rule 920310 (CRS3) not firing if no User-Agent is submitted

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#370]
920310 (CRS3) is meant to alarm if there is no Accept header. There are cases where an alarm is suppressed based on the User-Agent. However, given the construction of the rule, a request without a User-Agent will never trigger 920310, which is a false negative.

Possible solutions:
- 2nd rule covering this special case
- replace `@pm` with regex and check for empty header

Thoughts?

This issue evolved from a discussion in #366.

**Comment by csanders-git** [comment]
Now i know what you are saying specifically when we are talking about anomaly mode based scoring but  from a standalone perspective rule 920320 will trigger to prevent this issue. 
In anomaly mode this is an issue since 920320 is only tx.notice_anomaly_score. 
I will say that perhaps adding a 2nd rule covering the case in a high paranoid mode 2 or 3 might be the best approach. If i recall the user-agent being part of this check was already an attempt to reduce false positives.

**Comment by dune73** [comment]
@csanders-git : good remark about `920320` being notice. I overlooked that.

Covering the special case at a higher PL does not seem right to me as it allows a simple evasion at PL1 to go mostly unnoticed and it tears two rules with the same goal apart within the same rule file.

I think a PL1 sibling `920311` right after `920310` is the better solution:

```
SecRule REQUEST_HEADERS:Accept "^$" \
  ...id:920310
     SecRule REQUEST_METHOD "!^OPTIONS$" \
       "chain"
          SecRule &REQUEST_HEADERS:User-Agent "@eq 0"
          ...
```

That way the problem is contained at PL1 and within the same area in the rule file.

**Comment by csanders-git** [comment]
i'd eagerly accept such a pull request :-D

**Comment by dune73** [comment]
Can't resist such an invitation. Please consider #389 as my offering.

**Comment by csanders-git** [comment]
Nice job on this - I believe it is closed - if i am wrong reopen it :)
