### ISSUE TITLE
CRS 3.0-Rc1 - 920430 & 911100 triggered on lots of requests

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/owasp-modsecurity-crs#373]
Server: Debian Wheezy
PHP Version 5.4.45-0+deb7u3
Apache-npm-itk v2.2.22
libapache2-mod-security2: v2.8.0-2~bpo70+1
Modsec Crs:  v3.0.0-rc1

-----------------------

This new Crs version looks very promising. Thanks a lot for all this.

I have 2 warnings triggered on nearly all the requests, simple GET requests.. 

It seems the values from the variables defined in rule id 900012 are not well checked:
```
SecAction \
 "id:'900012',\
  phase:request,\
  nolog,\
  pass,\
  t:none,\
  setvar:'tx.allowed_methods=GET HEAD POST OPTIONS', \
  setvar:'tx.static_resources=jpg|jpeg|png|gif|js|css|ico', \
  setvar:'tx.allowed_request_content_type=application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/x-amf|application/json|text/plain', \
  setvar:'tx.allowed_http_versions=HTTP/0.9 HTTP/1.0 HTTP/1.1', \
  setvar:'tx.restricted_extensions=.asa/ .asax/ .ascx/ .axd/ .backup/ .bak/ .bat/ .cdx/ .cer/ .cfg/ .cmd/ .com/ .config/ .conf/ .cs/ .csproj/ .csr/ .dat/ .db/ .dbf/ .dll/ .dos/ .htr/ .htw/ .ida/ .idc/ .idq/ .inc/ .ini/ .key/ .licx/ .lnk/ .log/ .mdb/ .old/ .pass/ .pdb/ .pol/ .printer/ .pwd/ .resources/ .resx/ .sql/ .sys/ .vb/ .vbs/ .vbproj/ .vsdisco/ .webinfo/ .xsd/ .xsx/', \
  setvar:'tx.restricted_headers=/Proxy-Connection/ /Lock-Token/ /Content-Range/ /Translate/ /via/ /if/'"
```

The warnings I have don't make sense:
```
Warning. Match of "within %{tx.allowed_methods}" against "REQUEST_METHOD" required. [file "/etc/modsecurity/REQUEST-11-METHOD-ENFORCEMENT.conf"] [line "49"] [id "911100"] [rev "2"] [msg "Method is not allowed by policy"] [data "GET"] ...

Ruel id 911100 (rules/REQUEST-11-METHOD-ENFORCEMENT.conf):
SecRule REQUEST_METHOD "!@within %{tx.allowed_methods}"
```
GET is in the "allowed_methods".
```
Message: Warning. Match of "within %{tx.allowed_http_versions}" against "REQUEST_PROTOCOL" required. [file "/etc/modsecurity/REQUEST-20-PROTOCOL-ENFORCEMENT.conf"] [line "1051"] [id "920430"] [rev "2"] [msg "HTTP protocol version is not allowed by policy"] [data "HTTP/1.1"] ...

Rule id 920430 (rules/REQUEST-20-PROTOCOL-ENFORCEMENT.conf):
SecRule REQUEST_PROTOCOL "!@within %{tx.allowed_http_versions}"
```
HTTP/1.1 is in the "allowed_http_versions"

Is there a problem with the function 'within'?

See attached log for more info.

[event_28683.txt](https://github.com/SpiderLabs/owasp-modsecurity-crs/files/330538/event_28683.txt)

**Comment by lifeforms** [comment]
Hi @quenenni, thanks for your report!

I agree that these matches should not happen. You are correct, that the setup variables are not being used properly.

Since I've actually hit a very similar problem, I suspect that the variables are not set at the correct time.  Just yesterday we added a patch for that in #378. In short, we replaced `phase:request` with `phase:1` in the example config.

Could you check if doing that replacement in your setup.conf fixes the problem for you? :)

**Comment by quenenni** [comment]
The same as for https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/374, I'll test asap and report back here

**Comment by quenenni** [comment]
> Also, how are you including the setup.conf and the CRS rules? Are you including the setup.conf first from your httpd.conf, and then the CRS rules? (We should definitely document this better)

The file '/etc/apache2/mods-enabled/security2.conf' contains:
`
<IfModule security2_module>
        # Default Debian dir for modsecurity's persistent data
        SecDataDir /var/cache/modsecurity

        # Include all the *.conf files in /etc/modsecurity.
        # Keeping your local configuration in that directory
        # will allow for an easy upgrade of THIS file and
        # make your life easier
        Include /etc/modsecurity/*.conf
</IfModule>
`

From what I understand, the files are charged in alphabetic order and modsecurity.conf is the first conf file loaded, then modsecurity_crs_10_setup.conf, then all the REQUEST-* conf files and then the RESPONSE-* conf files.

**Comment by lifeforms** [comment]
@quenneni I think due to capitalization, REQUEST/RESPONSE are sorted first. I'm interested in fixing this structurally, but to test the hypothesis, could you include modsec + crs setup conf manually before the wildcard include? (You might need to temporarily put them in another dir to not include them twice) Please let me know the outcome!

**Comment by quenenni** [comment]
It seems you were right.
```
<IfModule security2_module>
        SecDataDir /var/cache/modsecurity

        Include /etc/modsecurity-conf/*.conf
        Include /etc/modsecurity/*.conf
</IfModule>
```
And I put modsecurity.conf and modsecurity_crs_10_setup.conf in /etc/modsecurity-conf/

Now everything seems to work nicely. 
Well, I have to do more tests, but I already don't have these non-stop warning about the rules 920430 & 911100.

Thanks a lot for your help (and sorry to not have seen that).

**Comment by csanders-git** [comment]
@lifeforms it is important to remember that this behavior (depending on your setup) is dependent on platform and OS :( 

Our recommendation should ALWAYS be to list out all files included. To further this point i'll share a bug I ran into earlier this week (And shared already with @dune73 )
It seems that when NGINX brings in rules it doesn't follow the natural ordering of naming scheme we expect. So even if you isolate setup.conf as a setup include. REQUEST-49-EVALUATION will still fire prior to most the other rules, making anomaly scoring ineffective without manually listing the files out. It should be noted that this is obviously fixed in v3 as we no longer have different code bases for the same functionality :-X

**Comment by csanders-git** [comment]
Closing this for now although we have great motivation to talk about this further in #368

**Comment by lifeforms** [comment]
@csanders-git I created #384 to track possible improvements for this scenario. If you have a fix for Nginx, please add it over there. I haven't run ModSec on Nginx yet, but I could set it up on FreeBSD.
