### ISSUE TITLE
Removal of platform dependent 920110

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#394]
The following rule just propagates up a warning from the Apache log. This functionality does not work in other web servers (Nginx and IIS) and is not going to be supported in 3.x (see https://github.com/SpiderLabs/ModSecurity/issues/1028). I think it makes some sense to remove this rule.

SecRule WEBSERVER_ERROR_LOG "@contains Invalid URI in request" \
  "msg:'Apache Error: Invalid URI in Request.',\
  severity:'WARNING',\
  id:920110,\
...

**Comment by zimmerle** [comment]
I would agree with @csanders-git. Having a rule that is just workable on a single environment is very confuse, specially because it is not clear that it is currently only available in Apache.

ModSec' reference manual about this variable:
https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#WEBSERVER_ERROR_LOG

Worth to mention that this variable is is only filled during the logging phase.

**Comment by dune73** [comment]
Agree with your conclusions.

**Comment by fgsch** [comment]
This is done. Closing.
