### ISSUE TITLE
Easing-in CRS execution (A/B) by pseudo random numbers

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#410]
https://www.netnea.com/cms/2016/04/26/easing-in-conditional-modsecurity-rule-execution-based-on-pseudo-random-numbers/

This idea can help people gradually adopting the CRS, by shifting bigger percentages of traffic to it.

**Comment by dune73** [comment]
Actually, this might also be the solution for the "shift from PL1 to PL2 without compromising security or kill the server with FPs". People could raise the paranoia level for some percentage of requests.

**Comment by csanders-git** [comment]
Although we love CSPRN's you might just be able to use  PERF_SREAD/ PERF_SWRITE

**Comment by dune73** [comment]
You mean I could use that perf data, save it into GLOBAL and use it for the next request? Wow! The possibilities are endless... Feeling like a crypto champ! ;)

**Comment by csanders-git** [comment]
You are now doing crypto on the level of PHP pre 5.4 when OpenSSL extensions were enabled. Everyone used to just use system(stat) - ugly but it is pretty random :-P

**Comment by dune73** [comment]
I have looked into this:
- PERF_SREAD is smaller then DURATION. By a factor of about 40 and it is actually contained in DURATION. So I get the feeling, it's not a good additional / alternative source of entropy even more so as I see a tendence for clustering which degrades quality.
- PERF_SWRITE and PERF_GC are not visible in the rules, as they are generated after phase:5. So you can see them in the audit logm, but that's about it.

What I could do is save the number in the GLOBAL resource and reuse on the next call. But I think this would not be worth the hassle / performance loss of writing an otherwise non-initialised resource.

**Comment by csanders-git** [comment]
yeah agreed - too bad :(

**Comment by dune73** [comment]
I saw that the need for TIME_EPOCH is very rare. In about 0.5% of the requests. I think I will replace that with the last digit of PERF_SREAD.

The plan is now to set a var like `tx.sampling_rate` in setup.conf with default 100. Then in a new rule file, I would test for this variable. If it is != 100, I would generate the random number and skip depending on the check. Can REQUEST-901... be pushed ahead to 902 or 903 to make room for the new file?

I plan to stick with a single percent-number as the only random number and also set a new final marker in the 999-file.

**Comment by csanders-git** [comment]
is there any reason you wouldn't want this to be 902 and leave common exceptions first?

**Comment by dune73** [comment]
I'd rather not do exceptions, if we want to skip the _whole_ ruleset.

**Comment by csanders-git** [comment]
makes sense... i'd be fine with it.

**Comment by dune73** [comment]
See #428.

**Comment by lifeforms** [comment]
It's a merge! Congrats!

Shall we close this? Or do you want to still add a sampling percentage for paranoia levels?

**Comment by dune73** [comment]
Let's close it and see how PL and sampling works in practice. Then, when we see a real need, we can think you to raise PL on a production site.
