### ISSUE TITLE
Regex in 920220 and 920240 Looking for URL encoded values... WHAT?

### ISSUE THREAD

**Issue by csanders-git** [SpiderLabs/owasp-modsecurity-crs#422]
These are two weird rules that i'm not sure about. Perhaps i'm misunderstand so i'm hoping someone can help. We know the URLs should contain URL encoded chars if a reserved char is provided in the query portion. It also MAY contain URL encoded cars for any other unreserved element. This brings us to the following rules, 920220 and 920240. It appears their goal is noble, to check if various aspects are correctly encoded using @validateUrlEncoding (we'll talk about this later). However they have a strange regex proceeding that goal.

`\%((?!$|\W)|[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})`

Now lets break this apart starting at the back. 
- %uXXXX encoding is not supported by the validateUrlEncoding (https://github.com/SpiderLabs/ModSecurity/blob/88bffb1e3eda8cc5e24965c9e06dec15f91be11a/apache2/re_operators.c#L4170). Or the W3c for the past 11 years (https://www.w3.org/International/iri-edit/draft-duerst-iri.html)
- It then checks for valid %XX encoded chars - hmmmm well these wouldn't trigger @validateUrlEncoding as it is the definition of what it is doing.
- Then we get the forward look ahead, which pretty much usurps the other checks and returns on any % NOT followed by a non char letter (really try and trigger any of the other options). WAIT! aren't those %'s followed by non-char letters what we want? Shouldn't those be the ones that fail validation? (i.e %%, %( , etc). 

Ok so we'll run the rule on like %xy - that's invalid... but!!!

But here is the real issue I have here. Apache automatically decodes parameters before handing them to  anything, in fact ModSecurity benefits from this as parameters will be already decoded when provided to the rule (REQUEST_URI is not, but ARGS is for instance). However, Apache is smart, when they receive an invalid decode they just don't decode it. For an example

If I had a page that just reflected a parameter 'x'. Sending the following URIs would have the following results

```
Request: http://localhost?printme=%40
Result: @ 

Request: http://localhost?printme=%w40
Result: %w40 
```

As can be seen invalid percent encoding within url's are simply treated as raw text. In fact they aren't really invalid as the RFC defines a valid encoding as `pct-encoded = "%" HEXDIG HEXDIG`. This makes perfect sense now as there is really no problem with it. However @validateurlencoding makes a probem with it. We will block on %w40 because there is a percent sign and w is out of range of a-f. But this is perfectly valid. Additionally, as far as I am aware this doesn't really directly or indirectly cause any vulnerabilities.

In face the only thing it seems URLs can't have is spaces, these WILL be encoded with +/%20 (dealer's choice). The rest is up to the user or link supplier to properly encode (weird huh, URL encoding isn't really automatically on URLs)

My vote is to remove these the first rules and rewrite  920240 with a check that makes sure that there is at least one equal sign (If you declared form-urlencoded elements must be provided as name/value pairs) and that there are no spaces or reserved chars (as these WILL be encoded here).and here we can use @validateurlencoding as percents will be encoded... but we shouldn't do that crazy regex check first.

```
SecRule REQUEST_HEADERS:Content-Type "^(application\/x-www-form-urlencoded|text\/xml)(?:;(?:\s?charset\s?=\s?[\w\d\-]{1,18})?)??$" "id:123,block,chain"
   SecRule REQUEST_BODY "@rx [\!\*\'\(\)\;\:\@\&\=\+\$\,\/\?\#\[\]\s]" "chain"
       SecRule REQUEST_BODY "!@rx \=" "chain"
           SecRule REQUEST_BODY "@validateUrlEncoding" ""
```

**Comment by michaelgranzow-avi** [comment]
I stumbled over this regex and was also struggling to make sense of it. I agree with your analysis: the first option (?!$|\W) is the only one needed. Something that doesn't match this won't match the other two options either. And conversely, anything that matches one of the last two options will already have matched the first option. Therefore, from a regex-matching point of view the last two options are pointless. However, from a semantics point of view, they are even wrong because they describe *valid* percent-encodings, so the presence of these sequences is no reason for concern and should not result in rejection of the request. validateUrlEncoding will happily accept them, so there is no functional problem, just a performance and readability issue.

I disagree with your opinion that percent-encoding doesn't need validation. Imagine a naïve percent-decoder that simply converts the two characters following a '%' without further checks. The sequence '%0w', for example, would be converted to ascii value 22, which is not a printable character and can easily cause unwanted behavior in an application. (Yes, this is a rather stupid thing to do, but the point of a waf is to protect such apps...). RFC 1738 classifies '%' as an unsafe character and states that "all unsafe characters must always be encoded within a URL". Therefore, a string that contains "%0w" is not a valid URL and should be rejected. Furthermore, a trailing '%' isn't allowed either, but the regex in the rule accepts it (validateUrlEncoding will then reject it).

My initial suggestion would be to replace the regex with
```
  \%((?!([0-9a-fA-F]{2}|u[0-9a-fA-F]{4})))
```
This would reject strings that contain an invalid percent encoding. In theory we then don't even need validateUrlEncoding in a chained rule. However, validateUrlEncoding doesn't accept the non-standard %uXXXX format. A better regex would therefore be
```
 \%(?![0-9a-fA-F]{2})
```
This will enforce exactly the same format that validateUrlEncoding also enforces. It then becomes a matter of performance (or taste), which one to use. A dedicated function like validateUrlEncoding can be expected to perform better than a regex, but having the validation in the form of a regular expression right there in the rule as opposed to hidden in a C function improves readability. If validateUrlEncoding performs significantly better than the regular expressioncheck, the rule should be changed to

```
SecRule REQUEST_HEADERS:Content-Type "^(application\/x-www-form-urlencoded|text\/xml)(?:;(?:\s?charset\s?=\s?[\w\d\-]{1,18})?)??$" \
  "phase:request,\
   rev:'2',\
   ver:'OWASP_CRS/3.0.0',\
   maturity:'6',\
   accuracy:'8',\
   t:none,\
   block,\
   msg:'URL Encoding Abuse Attack Attempt',\
   id:920240,\
   tag:'application-multi',\
   tag:'language-multi',\
   tag:'platform-multi',\
   tag:'attack-protocol',\
   tag:'OWASP_CRS/PROTOCOL_VIOLATION/EVASION',\
   severity:'WARNING',\
   chain"
     SecRule REQUEST_BODY|XML:/* "@validateUrlEncoding" \
       "setvar:'tx.msg=%{rule.msg}',\
        setvar:tx.anomaly_score=+%{tx.warning_anomaly_score},\
        setvar:tx.%{rule.id}-OWASP_CRS/PROTOCOL_VIOLATION/EVASION-%{matched_var_name}=%{matched_var}"
```

Regarding your suggestion:
```
SecRule REQUEST_HEADERS:Content-Type "^(application\/x-www-form-urlencoded|text\/xml)(?:;(?:\s?charset\s?=\s?[\w\d\-]{1,18})?)??$" "id:123,block,chain"
   SecRule REQUEST_BODY "@rx [\!\*\'\(\)\;\:\@\&\=\+\$\,\/\?\#\[\]\s]" "chain"
       SecRule REQUEST_BODY "!@rx \=" "chain"
           SecRule REQUEST_BODY "@validateUrlEncoding" ""
```
IIUCC, your intention is to fully validate a url-encoded request body. However, there seem to be a few problems with this rule. For a request to be rejected the following conditions all have to be met:

1. It must contain one of the reserved characters
2. it must not contain an equal sign
3. it must contain an invalid percent encoding

Conditions 1. and 2. can be mutually exclusive if condition 1. was met because of an equals sign. The problem here is that the equals sign has the meaning of tokenizing a line in the body. It must be present as the separator between key and value, but an equals sign inside a value would have to be percent-encoded. So condition 1. must be applied to all keys and all values, not to the request body as a whole.

**Comment by fgsch** [comment]
This issue has been overtaken by events. 

Please open a new issue if this is still a concern.
