### ISSUE TITLE
JSON values in cookies constantly trigger 6+ rules making 2.2.6 unusable for these cookies

### ISSUE THREAD

**Issue by OrySegal** [SpiderLabs/owasp-modsecurity-crs#46]
Hi,

There is a set of rules in 2.2.6 (mostly SQL Injection) that constantly generate false positives on complex cookie values (e.g. JSON structures).

If it was one or two rules, I would say it's fine, but when it's 6 or more rules that constantly trigger on these cookies, I think we have a problem - this can't be fixed with a threshold setting.

In addition, I think that these rules are really not doing their task well - I don't think that the triggers you will see below are supposed to trigger.

Here is the cookie:

MyCookie={"v":1,"rid":"1371546489873_699561","to":5,"c":"http://www.some.site/page.aspx?a=5","pv":2,"lc":{"d0":{"v":2,"s":true}},"cd":0,"sd":0,"f":1371546904751}
## Rules triggered:
- 973333 - matching string is:
  - ","to":5,"c":"http://www.some.site/page.aspx?a=
- 981172 - matching strings are:
  -  {"v":1,"rid":" 
  -  ://www.some.site/page.aspx?a=5","pv":2,"lc":{"
  -  }},"cd":0,"sd":
  -  ","to":5,"c":"
  -  ":{"v":2,"s":
- 981243 - matching strings are:
  -  ":1,"
  -  ":"137
  -  ":5,"
  -  ":2,"
  -  ":{"
  -  ":{"
  -  ":2,"
  -  ":0,"
  -  ":0,"
  -  ":13
- 981245 - matching strings are:
  -  ":1,"r
  -  ":"1371546489873_699561","t
  -  ":5,"c
  -  ":"http://w
  -  ":2,"l
  -  ":{"d0":{"v
  -  ":2,"s
  -  ":true}},"c
  -  ":0,"s
  -  ":0,"f
- 981246 - matching string is:
  -  "rid":"
- 981257 - matching strings are:
  -  ,"rid
  -  ,"to":5,"c":
  -  ,"pv":2,"lc":{
  -  ,"s":true}},"cd":0,
  -  ,"f":1371546904751}

**Comment by sakalajuraj** [comment]
+1

**Comment by franbuehler** [comment]
I found this old issue and looked into it.
The rules are still there, but none of the rules are at PL1.

```
973333,941340 - PL2
981172,942420 - PL3
       942421 - PL4
981243,942370 - PL2
981245,942260 - PL2
981246,942340 - PL2
981257,942200 - PL2
```

If I test with the value `{"v":1,"rid":"1371546489873_699561","to":5,"c":"http://www.some.site/page.aspx?a=5","pv":2,"lc":{"d0":{"v":2,"s":true}},"cd":0,"sd":0,"f":1371546904751}` in a post body instead of the cookie and if I set the "Content-Type: application/json" the false positives are gone.
As mentioned in the referenced issue (https://github.com/SpiderLabs/ModSecurity/issues/687), the JSON parser does not deal with JSON values in cookies. It works only in a post body.

Now the question is: do we close this issue because there are no more false positives on PL1 and because the Core Rule Set project is not able to resolve this issue?

**Comment by csanders-git** [comment]
I think we close the issue for now because eventually @victorhora @zimmerle  and the modsecurity team will add support for processing specific parameters of the request as JSON instead of either the whole thing or nothing. This will then allow us to resolve this issue not just by making the rules higher level.

**Comment by devdeadcode** [comment]
While I'd really like to appreciate @victorhora , @zimmerle and other team members' efforts on trying to add support for processing specific parameters of the request as JSON, do we have any update on this?
