### ISSUE TITLE
What to do with people using the CRS2 setup.conf with CRS3?

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#479]
The anomaly scoring limit var changed its name to name but one of the several significant changes.

So what if people take the easy path from CRS2 to CRS3 without updating their setup.conf. In the worst case, the CRS would stop blocking things with CRS3.

It's too late for RC1, but we need a solution for the final release. Tagging this RC2.

**Comment by lifeforms** [comment]
Using an old config would be horrible, but thanks to the setup check rule (tx.setup_done), at least they will get informative warnings in their logs about not having a modern config file.

There are so many changes (for instance the format changes of allowed_extensions and restricted_headers) that we should just make the recommendation to start over from the new template rather than edit the old.

**Comment by lifeforms** [comment]
Accidentally disabling the CRS might be scary. But giving 403 by default might also not be very popular. Hard to say which choice is best.

Other various ideas to improve the upgrading experience: 

I realized, if we should remove self-contained mode in the future, then a user doesn't need a setup file at all any more. (Just move the default actions to 901 which is the only thing active by default in the new setup)

If we want to be proactive for variables with changed syntax, we could also try to validate them with a regexp and warn on old syntax.

**Comment by lifeforms** [comment]
*Decision:* change rule 901001 to log,auditlog,deny,status:500,severity:CRITICAL. Fix the log message to explain that the request is blocked because of missing configuration.

**Comment by lifeforms** [comment]
PR is in #587 587.
