### ISSUE TITLE
Remove t:none everywhere

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#487]
We are setting SecDefaultAction without any transformation. `t:none` in all too many rules is thus bloat.

Not sure if 3.0.0RC2 or 3.1.0.

**Comment by lifeforms** [comment]
More of a cosmetic thing so would say 3.1

**Comment by dune73** [comment]
If it's cosmetic, why don't we simplify the rules by removing it for RC2? ;)

**Comment by lifeforms** [comment]
Well because we might inadvertently introduce bugs while doing it. After people have tested RC1, it would be weird to go change rules again. Generally one does that before declaring the branch a release candidate. If we think this diff is useful (and I agree it would be nice) it would reflect better on us if we'd make the change before sending out the RC for testing. But it's not that high-prio to me personally.

**Comment by dune73** [comment]
Makes sense.

**Comment by csanders-git** [comment]
t:none is there because it is possible for people to add transformations to SecDefaultAction. While we don't set any of these, because this is considered poor form, there is nothing stopping someone from configuring these settings and this would potentially introduce unintended transformations to rules that don't have t:none.

**Comment by lifeforms** [comment]
@csanders-git True, but we're resetting the default action in the setup conf though, so we may assume that the default is clean.

At the other hand, including `t:none` would help people who copypaste rules from the CRS into their own contraptions. Don't know if a lot of people do this though.

**Comment by csanders-git** [comment]
I don't think we should make assumptions that the setup.conf won't be modified, this is my primary concern.

**Comment by fgsch** [comment]
So what's the consensus here? Should we remove it or not?
If not let's close this ticket.

**Comment by dune73** [comment]
@csanders-git has a point that there is some risk involved and the bloat is not excessive. 

So I'm closing this for the time being.
