### ISSUE TITLE
Reverse engineer source-files for all Perl Regex-Assembly rules

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#488]
I think we need to be able to edit and regenerate these regexes in a clean way.

We're talking about 3 dozens of rules AFAICS.

**Comment by csanders-git** [comment]
can you explain what you mean here in a little more detail?

**Comment by lifeforms** [comment]
@csanders-git Many oldschool rules have assembled regexps, which exist only in the repo in compiled form e.g. `(?i:(?:m(?:s(?:ysaccessobjects|ysaces|ysobjects|ysqueries|ysrelationships|ysaccessstorage|ysaccessxml|ysmodules|ysmodules2|db)|aster\.\.sysdatabases|ysql\.db)|s(?:ys(?:\.database_name|aux)|chema(?:\W*\(|_name)|qlite(_temp)?_master)|d(?:atabas|b_nam)e\W*\(|information_schema|pg_(catalog|toast)|northwind|tempdb))`

This makes them hard to check/maintain/update.

The easiest would be to contact the original rule authors to ask if they still have the source files. Otherwise it could be a bit of manual work or maybe a fun algorithms programming exercise.

**Comment by dune73** [comment]
This.

**Comment by csanders-git** [comment]
Haha, yeah this is really a serious annoyance now that we're trying to build regression tests :) good call.

**Comment by lifeforms** [comment]
Once we obtain the sources, we should also convert the rules to pmf where possible (i.e. case-insensitive, regexp contains no metacharacters).

**Comment by lifeforms** [comment]
According to 951 file comment, its regexps come partly from [sqlmap errors.xml](https://raw.githubusercontent.com/sqlmapproject/sqlmap/master/xml/errors.xml) and Arachni (link broken).

**Comment by dune73** [comment]
Ofer Shezaf has shared his ancient 1.6 build system with the project. It looks like this is all we need.

 @csanders-git, @lifeforms and I have a copy.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
