### ISSUE TITLE
932150 (RCE: unix) '.' (dot) FPs (rare but still)

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#518]
This is a drupal site.

Matches:
```
data "Matched Data: en/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: en/js/clients_glue/locality/pa_glue_service/. Gallen"
data "Matched Data: en/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: en/js/clients_glue/locality/pa_glue_service/. Galle"
data "Matched Data: en/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: en/js/clients_glue/locality/pa_glue_service/. Gall"
data "Matched Data: en/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: en/js/clients_glue/locality/pa_glue_service/. Gal"
data "Matched Data: en/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: en/js/clients_glue/locality/pa_glue_service/. G"
data "Matched Data: en/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: en/js/clients_glue/locality/pa_glue_service/. "
data "Matched Data: it/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: it/js/clients_glue/locality/pa_glue_service/. m"
data "Matched Data: it/js/clients_glue/locality/pa_glue_service/.  found within ARGS:q: it/js/clients_glue/locality/pa_glue_service/. "
```

**Comment by lifeforms** [comment]
`.` 😰

**Comment by lifeforms** [comment]
The matched command is the `.` (source command).

Since we also match if a command is prefixed with an `/arbitrary/path`, the rule matches. `it/js/clients_glue/locality/pa_glue_service/` is seen as the path component. `.` is the command.

The `.` command is a special one in the list. It's a shell built-in, so it can never be executed with a path.

We could split `.` off to a separate rule, and omit the path component from that rule.

I have also seen FPs where `.` causes FP in Markdown, for instance if people post:

```
Try `blah`.
```

In that pattern, the last backtick is seen as a command separator (which it certainly can be in this pattern). However, if this specific pattern causes much FP, the problems might outweigh the detection of this specific pattern.

If the `.` command would be moved to a separate rule, we could also drop the backtick from its regexp.

**Comment by lifeforms** [comment]
PR is in #594.
