### ISSUE TITLE
Import Shellshock rules

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#551]
The Shellshock vulnerability is old news today, but I still see many scans for it daily.

Even if every machine would be patched by now (ha ha that's a good one), it's very interesting to alert on this type of probe.

I am using the following ModSec rules published by Red Hat. But they didn't state a license. We probably have to ask.

https://access.redhat.com/articles/1212303

**Comment by dune73** [comment]
Funny, we have not thought of this before.

Confirm: I see the probes regularly as well.

As for the rule / license: I do not think we need a license to copy the REGEX, even more so as that is a straight adoption of the CVE proof of concept. The transformation are obvious, the rest of the rule would be written from scratch anyways. Linking to their article would only be fair though.

I wonder if the said regex is still up to the task with subsequent shellshock probes. Or we simply ignore them because we all use the regex as proposed in the said redhat article.

**Comment by shrv** [comment]
I already use such a rule. I created it myself
#Bash Environment Variable Command Injecion
SecRule REQUEST_HEADERS:User-Agent "(\(\).?\{[a-zA-Z_0-9\;: ]*\}.*bash)"\
"phase:2,t:none,block,msg:'Bash Environment Variable Command Injecion',rev:'2',ver:'CP_CRS/2.2.9',maturity:'9',accuracy:'9',id:'XXXXXX',tag:'CP_CRS/POLICY/CGI-Bash',\
tag:'WASCTC/WASC-20',tag:'OWASP_TOP_10/A1',tag:'OWASP_AppSensor/EE2',tag:'CVE-2014-6271',severity:'2',logdata:'%{matched_var}',\
setvar:'tx.msg=%{rule.msg}',setvar:tx.anomaly_score=+%{tx.blocking_anomaly_score},\
setvar:tx.%{rule.id}-CP_CRS/POLICY/CONTENT_TYPE_NOT_ALLOWED-%{matched_var_name}=%{matched_var}"

If you think necessary, you can use it. Or remake it as you think is necessary.

**Comment by dune73** [comment]
Thanks @shrv. This is very close to what I had in mind.

**Comment by lifeforms** [comment]
We included this in CRS3 so this issue can be closed!
