### ISSUE TITLE
942410: add Oracle utl_http, utl_file

### ISSUE THREAD

**Issue by lifeforms** [SpiderLabs/owasp-modsecurity-crs#609]
Rule 942410 detects `utl_inaddr` (useful for blind SQL injection in Oracle) but not `utl_http` which can be used for similar purposes and `utl_file` which can read files.

**Comment by franbuehler** [comment]
As you see in issue #811, `utl_http` and `utl_file` are also detected, but they don't appear at the same position.
That's why I think the regexp in rule 942410 could be revised.
The commands seem to be somewhat distributed and the rule is not consistently optimized.
I think, this issue could be closed.

**Comment by dune73** [comment]
Agreed.

@lifeforms: OK with closing?

**Comment by lifeforms** [comment]
Further discussion in #811!
