### ISSUE TITLE
tx.setup_done -> tx.crs_version

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#615]
We would like to branch depending on the CRS version. As this is a script-generated config, it would be very convenient to include rules (exclusion rules or even includes) depending on the CRS version.

Now tx.setup_done is being set in CRS3 and we can use this to branch between CRS2 and CRS3. However, once CRS3.1 comes out, we will need an additional variable. We can set this ourselves of course, but that's a bit of a nuissance.

So I wonder if it would not be beneficial to replace tx.setup_done by a tx.crs_version variable. If it is not set, we do the 500 we have defined. If it is 3.0.0, all is fine. In the future, we can check for the correct version in the init file. If tx.crs_version is < than version defined in 901, then we can tell user to replace his setup.conf. I think that would be very beneficial.

Sorry for being very late in the process. It only occurred to us right now.

[Credit: This is based on a suggestion by Franziska, who is planning CRS migration here.]

**Comment by lifeforms** [comment]
Good idea to set a variable, though it costs a bit of performance. I think this variable should probably be set up in initialization, so that it's raised when a user updates their rules, right? They might keep using their old crs-setup.conf (since this is not version tracked). Is there a way to inspect the version string (SecComponentSignature) so that we might not need a variable?

**Comment by lifeforms** [comment]
Oh, I misunderstood, sorry. You were discussing to check if  the version of crs-setup.conf is valid. Yeah, that makes sense. We can warn if we have made breaking changes - though I think we should do this rarely. In general an old config version should just keep working. We could put `300` instead of `1` in the last line.

**Comment by dune73** [comment]
Yep, that's very close to what I have in mind.

The problem with the ComponentSignature is, that you can't read it AFAIK. 

If we go for alpha numerical (-> `3.0.0-rc2`) the 901 file will also work without changing the rule and we keep all the options open. `300` is a bit more limited in this regard and if we need `300` we can transform `3.0.0-rc2` into `300` via a capture action.

All we would have to change is the name of the variable.

**Comment by lifeforms** [comment]
But if we use `300` we can do a simple `@ge` to match on it.

**Comment by lifeforms** [comment]
I'd name it `crs_setup_version` by the way, since it denotes the version of the user's setup file (not the rule files).

**Comment by dune73** [comment]
+1 for the `crs_setup_version`, but `300` demands explanation and limits us in the future. With alphanumerical version, we can put there whatever we want to.

And we can always do `"^([0-9]+)\.([0-9]+)\.([0-9]+)"  "...,capture,setvar:tx.crs_setup_version_numerical=%{TX.1}%{TX.2}%{TX.3}"`

**Comment by dune73** [comment]
@csanders-git : Are you OK with that change so late in the cycle and if you are: numerical or alphanumerical.

**Comment by csanders-git** [comment]
i'd go numeric but it's a great idea!

**Comment by dune73** [comment]
Closing in favor of PR #616.
