### ISSUE TITLE
getting error when reload apache

### ISSUE THREAD

**Issue by broros** [SpiderLabs/owasp-modsecurity-crs#621]
debian 8.6
apache 2.4.10

AH00526: Syntax error on line 51 of /usr/share/modsecurity-crs/optional_rules/modsecurity_crs_16_session_hijacking.conf:

**Comment by dune73** [comment]
Thanks for writing in.

This is a bug in a rarely used part of the old Core Rules release.

In the newest CRS3 RC2 version, this bug is gone.

I definitely recommend testing out our RC2. It has lots of improvements over the version you are now running. You can download a copy from the releases page or 
https://github.com/SpiderLabs/owasp-modsecurity-crs/releases/tag/v3.0.0-rc2

If you could help test the new version, it would be very welcome. While this alert will be solved for you, we are always looking for more comments and experiences.

**Comment by broros** [comment]
ok, is the new version ( 3.0) going to be released in debian 9? the current version of debian only supports 2.2.9

**Comment by dune73** [comment]
I can not speak for the debian project. But given the debian packaging means that the include the standard files in one of their packages, then you can very easily replace the debian rules with the standard CRS release files copied to the respective position by hand. Until debian catches up, which I am sure it will sooner or later.
