### ISSUE TITLE
Trusting X-Forwarded-For for real_ip collection

### ISSUE THREAD

**Issue by 0xd012** [SpiderLabs/owasp-modsecurity-crs#653]
Hi,

Using SecRule REQUEST_HEADERS:x-forwarded-for "^\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b" as real_ip if available leads to potential mitigation bypass if this header is not trusted (if provided by the attacker). A similar issue as using ua_hash for constructing real_ip.

Is it a voluntary default behavior comparing to rely on remote_addr by default?

Regards,

**Comment by lifeforms** [comment]
Nice find! I can confirm that this untrusted header is used to override the actual source IP in ratelimit decisions, geolookup and RBL checks.

If DoS rateliming is being used, it also allows you to lock out other users by spamming the server with their IP addresses in `X-Forwarded-For` ;)

We should not trust this header. We can't simply cull the functionality, because then people using reverse proxies are in trouble. Maybe we should add a `crs-setup.conf` setting to list some IP ranges containing allowed proxies -- and only trust this header when it's coming from them.

Relying on the attacker-controlled UA is a known issue on the list to be resolved, it seems that we should solve this at the same time.

**Comment by dune73** [comment]
Does not mod_remoteip play into this as well? It's a complicated module, I know. But if done correctly, you can control the acceptable IPs for this header.
 
Generally, it is true, that all this client identification that we perform is somehow fishy.

**Comment by 0xd012** [comment]
Yes, mod_remoteip module operates this way but only used/useful in architectures where `X-Forwarded-For` is correctly populated. It is not the case when the web server is the layer 7 endpoint.

**Comment by lifeforms** [comment]
We removed the reliance on `X-Forwarded-For` in version 3.0.1.

This means if you use authorized proxies, you need to use mod_remoteip module.

**Comment by aaronmaxlevy** [comment]
@lifeforms Since mod_remoteip is specific to Apache, how do you suggest folks using ModSec 3.x with Nginx handle this issue?

e.g. in my environment we are using HAProxy to terminate SSL and then send traffic to Nginx/ModSec . We are currently deleting the value of the X-Forwarded-For header when it comes in, so that the only entity setting its value is HAProxy.

For the above reason, X-Forwarded-For is considered a trusted header in our environment and ideally we'd be able to rely on it.

Curious what your thoughts are on this.

Thanks!
-Aaron

**Comment by dune73** [comment]
I guess that does away with the mitigation and your are free to use the header to create the collection, you might have to rewrite the rules a bit, though. We have not looked into this so far.

Are you working with ModSec3 on NGINX? What are your experiences?

**Comment by spartantri** [comment]
Hi Aaron,

I had the same issue since real_ip variable was introduced without checking the origin so I modified slightly the initialization rule 900019 to set up my trusted proxies, some balancers use different headers to send the original client ip which can be adjusted easily in the chained rule.

```
SecRule REMOTE_ADDR "@ipMatch 192.168.1.100,192.168.1.50,10.10.50.0/24" \
  "id:'900019', \
  phase:1, \
  nolog, \
  pass, \
  chain"
  SecRule REQUEST_HEADERS:x-forwarded-for "^\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})\b" \
    "t:none, \
    capture, \
    setvar:tx.real_ip=%{tx.1}"
```
Cheers!

**Comment by lifeforms** [comment]
Hi Aaron,

Personally I would always advise using webserver functionality to overwrite the proxy's IP with the real client's IP.

Benefit is that your application also transparently sees the client's IP address and you don't have to configure the trust for your proxies in various places. Usually these modules also have more advanced configuration options, and support more interesting cases properly, which is hard to do with an in-CRS solution (like, for instance, when you (or the client) uses multiple layers of proxies - causing a chain of `X-Forwarded-For` entries, which need to be checked for trust one-by-one)

In Nginx there is the `ngx_http_realip` module which seems to do the same thing. http://nginx.org/en/docs/http/ngx_http_realip_module.html

**Comment by jsfgreen** [comment]
So even if I do this:

    SecAction \
        "id:901321,\
        phase:1,\
        pass,\
        t:none,\
        nolog,\
        initcol:global=global,\
        initcol:ip=%{x-forwarded-for}_%{tx.ua_hash},\
        setvar:'tx.real_ip=%{x-forwarded-for}'"

It won't work?  Because that would explain why ModSec isn't blocking anyone... I tried the above in `REQUEST-901-INITIALIZATION.conf` before I found this thread.  So, just to be clear, is using mod_remoteip really the _ONLY_ way to get ModSec to block attackers by the x-forwarded-for header?
