### ISSUE TITLE
WordPress false positives

### ISSUE THREAD

**Issue by tomsommer** [SpiderLabs/owasp-modsecurity-crs#660]
I have a ton of audit logs with false-positives for WordPress /wp-admin/admin-ajax.php and /wp-admin/post.php (Ran CRS 3.0.0 on 100.000 websites for a second, until I had to turn it off). Exclusions were enabled.

If you are interested in the logs, for further improvement, is there anywhere I could send them? I can't share them publicly.

**Comment by dune73** [comment]
This is very interesting. Are we talking 100K websites? Wow. 

If you are into this sort of game, then look into the sampling mode. It let's you funnel n percent of requests into the CRS and all the other requests bypass the rule set. A little bite of tweaking could make this n promille. Sampling mode is documented in the crs-setup.conf and really simple. Ideally you combine this with a high anomaly threshold. That means you can let it run in the background, your disks will manage and the users are unaffected. Then we fix the issues together and then you raise the sampling percentage slowly.

If you are able to share your logs, we can guarantee safe handling. But I will let @lifeforms respond as he has been working on the WP rule exclusions. 

You are developing into a key player for the improvement of the quality of the WP rule exclusions.

**Comment by lifeforms** [comment]
Yeah, let's work together. Your data could be very useful! I think most of it likely comes from WordPress plugins. We are only covering WordPress core in 3.0.0 now. I personally would be totally for covering common plugins though. The beauty of having a log sample for 100k domains is that we have a much better picture of which plugins are common. My own data is biased because at my work place we allow only a limited number of plugins. Data from vhosting will give a much better picture.

If we start supporting many plugins, the exclusion rules could blow up into the hundreds or more though. I wouldn't mind doing the legwork on this data dump, but what goals do we set for the CRS project in terms of plugin coverage? Or shall we look at the log data first and make a choice later? Maybe it's a tractable number of separate plugins and it won't require a rethink of our design.

@tomsommer  If you want to send the log data securely, you can find my e-mail address and PGP key at: https://lifeforms.nl/contact If the log is large, it's best if you host it on a https site behind a .htaccess password and send me the link. I will treat it confidentially and keep the data in EU. That said, you might want to spend a bit of time removing things like password strings if possible.

**Comment by dune73** [comment]
I think an 80:20 approach is useful here. I would cover the set of plugins that allow us to cover 80% of the sites. I am quite sure that set is not overly big. (Of course I do not really know, but I would be surprised if the distribution would be different).

http://whatwpthemeisthat.com/top-plugins.html has usage percents. To me, this reads like there are only 11 plugins that are installed on more than 1% of sites (data behind the stats might be a bit shaky, but you get the idea).

**Comment by dune73** [comment]
@lifeforms / @tomsommer : What is the status of the delivery of the logs? If this has been done, then we should open separate issues. Either way, this one should be close.

Keeping it open for the time being to hear an update.

**Comment by tomsommer** [comment]
Sorry guys, I'm swamped at the moment. We would still love to help out.

Currently we are very dependant on our own set of modsec rules, so having to set these rules on standby while running the owasp rules in collection-mode is it a bit of an issue. Thoughts? I guess 10 minutes of sample-data should be enough though.

**Comment by dune73** [comment]
10min of sample data would be great.

Outside of that, the idea of CRS3 is to be able to put them next to other existing rules without any problem. But of course, if you interfere with the CRS3 anomaly scoring variables, then this won't work.

**Comment by lifeforms** [comment]
Closing this issue since it's been inactive for some time. @tomsommer if you still have some FP data that you want to share with us, we will be delighted to look at it. It could be quite a bit of a project, but it would be very useful to the community.
