### ISSUE TITLE
(FP) 981246 - Detects basic SQL authentication bypass attempts 3/3

### ISSUE THREAD

**Issue by D3VL-Jack** [SpiderLabs/owasp-modsecurity-crs#692]
I've had to disable the rule with ID 981246 because of the attached post data causing a false-positive.
https://gist.github.com/VoidTyphoon/38b90150c6411309d4aa250701091a4e

**Comment by dune73** [comment]
Thank you for reporting. 

The CRS2 rule is 942340 in CRS3. 942340 is a paranoia level 2 rule and thus no longer enabled in the default install.

Your post data is extremely large and triggers a ton of stuff. Given this is PL2, I do no think we will fix it.

**Comment by csanders-git** [comment]
Closing this issue, if you believe this was done in error, please reopen it. Generally 2.2.x has pretty false positive prone default settings. It is recommended that you upgrade to 3.x if possible otherwise false positives in 2.x are not generally fixed by the development team. We invite you to submit a patch for it however as we still accept those.
