### ISSUE TITLE
(FP) 981242 - Detects classic SQL injection probings 1/2

### ISSUE THREAD

**Issue by D3VL-Jack** [SpiderLabs/owasp-modsecurity-crs#693]
I've had to disable the rule with ID 981242 because of the attached post data causing a false-positive.
https://gist.github.com/VoidTyphoon/38b90150c6411309d4aa250701091a4e

**Comment by dune73** [comment]
CRS2 rule 981242 maps to PL2 rule 942330 in CRS3. The rule is thus no longer enabled by default. I suggest you update your installation. Otherwise, the same comments as the ones for #692 apply.

**Comment by csanders-git** [comment]
Closing this issue, if you believe this was done in error, please reopen it. Generally 2.2.x has pretty false positive prone default settings. It is recommended that you upgrade to 3.x if possible otherwise false positives in 2.x are not generally fixed by the development team. We invite you to submit a patch for it however as we still accept those.
