### ISSUE TITLE
(FP) 981240 'Detects MySQL comments

### ISSUE THREAD

**Issue by D3VL-Jack** [SpiderLabs/owasp-modsecurity-crs#694]
I've had to disable the rule with ID 981240 because of the attached post data causing a false-positive.
https://gist.github.com/VoidTyphoon/38b90150c6411309d4aa250701091a4e

**Comment by dune73** [comment]
CRS2 rule 981240 maps to PL2 rule 942300 in CRS3. It's thus the same situation as with #692 and #693. 

What I forgot to mention: These rules were removed from the default installation because the were known to cause false positives. Starting with PL2 (default is PL1), false positives are expected.

**Comment by csanders-git** [comment]
Closing this issue, if you believe this was done in error, please reopen it. Generally 2.2.x has pretty false positive prone default settings. It is recommended that you upgrade to 3.x if possible otherwise false positives in 2.x are not generally fixed by the development team. We invite you to submit a patch for it however as we still accept those.
