### ISSUE TITLE
(FP) 981245 - Detects basic SQL authentication bypass attempts 2/3

### ISSUE THREAD

**Issue by D3VL-Jack** [SpiderLabs/owasp-modsecurity-crs#695]
I've had to disable the rule with ID 981245 because of the attached post data causing a false-positive.
https://gist.github.com/VoidTyphoon/38b90150c6411309d4aa250701091a4e

**Comment by dune73** [comment]
CRS2 rule 981245 maps to PL2 rule 942260 in CRS3. See the comments in #692, #693 and #694.

**Comment by csanders-git** [comment]
Closing this issue, if you believe this was done in error, please reopen it. Generally 2.2.x has pretty false positive prone default settings. It is recommended that you upgrade to 3.x if possible otherwise false positives in 2.x are not generally fixed by the development team. We invite you to submit a patch for it however as we still accept those.
