### ISSUE TITLE
Support for older ModSecurity

### ISSUE THREAD

**Issue by ghost** [SpiderLabs/owasp-modsecurity-crs#741]
I would like to ask for support for an older version of ModSecurity.

CentOS is a long term supported distro based on RHEL with a 10-year support (end of production is at 2024). The latest ModSecurity version with CentOS 7.3 is mod_security-2.7.3. By requiring ModSecurity 2.8, it means CentOS is left out of CRS version 3.

Please consider supporting modsecurity 2.7.

Thank you.

**Comment by dune73** [comment]
You are effectively asking volunteers to continue to support outdated software for another seven years in our spare time and for free. Maybe you should ask RHAT / CentOS to provide you with backported version of CRS3 until 2024.

Effectively, there are only three rules which depend on ModSec 2.8. These are the rules that depend on the new libinjection libarary introduced in 2.8.0 (-> 941100, 941101, 942100). As it turns out, these rules are very strong. You can remove them from the files and CRS3 will work with 2.7.3. Probably until 2024. But you are also limiting your ability to detect SQLInjections until 2024.

Long term releases are a compromise between bleeding edge security and rock stable support. It is ultimately your choice, but I would advise you to run the latest ModSec on your CentOS. This may involve compiling it yourself - or upgrading to a later version.

**Comment by lifeforms** [comment]
Another option might be to use a separate reverse proxy (layer) where you can run the newest version of ModSecurity, and keep running your web application on the old CentOS.

**Comment by ghost** [comment]
So all you understood, is that somehow I require volunteers to support "outdated" software for seven years, in their spare time and for free...  wow talk about inferring nonsense out of nowhere. Someone got his panties in a twist :)

**Comment by dune73** [comment]
You asked a question and you got a response with advice and an optional solution to your needs within 15 minutes. Yet you continue to complain. ;(
