### ISSUE TITLE
SQLi bypass at PL3

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#780]
Ivan Novikov has been able to bypass our SQLi rules at PL3.

``` 
curl 'localhost/index.html?id=1%20or%20true'
``` 
Passes with score 0 at PL3 and only gets 5 at PL4. Reminds me a bit of #747 where we had an XSS bypass due to a missing transformation. That's probably the direction to fix this too.

**Comment by lifeforms** [comment]
This type of injection (unquoted) could be very hard to block because the chances of FP would be very high. You'd also need to chase payloads like `2 or 1` (since `1` would cast to `true`).

I submitted some similar examples to libinjection one time: https://github.com/client9/libinjection/issues/110 Probably the author has been hesitant because of FP detecting these would cause.

And we had a discussion in issue #448.

Doing something against them in PL3 might be interesting though.

**Comment by dune73** [comment]
@client9 got back today with regards to the PL4 bypass. He is eager to attack this.

I also think it's a libinjection and a PL3 issue. I would not try and catch this on PL1 and PL2 - too many FPs.

**Comment by dune73** [comment]
@zimmerle confirms they are waiting for a fix in libinjection. This would lead to a new ModSec release with an improved libinjection. We could then leave this for the moment in those hands.

**Comment by client9** [comment]
`1 or true`  yuck.

 I agree with @lifeforms .  Detection is not the hard part, false positives are.

libinjection will turn this into "1 OR 1" or "1 AND 1", and that *definitely* will have false positives.  

For very short SQLi, i actually do recommend regex or direct matching, since it's easier to control if the rule is on or not (vs. libinjection).  Some people will want it, other won't.. and having it as a LUA rule is better then rebuilding/reinstalling.

What do you think?

n

**Comment by dune73** [comment]
Hmm. But libinjection will only catch it, if the complete argument is "1 OR 1" and I doubt that will lead to many FPs. I see "1 OR 1 possibly show up somewhere in the middle of some free text, but rather not on it's on, or am I wrong?

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
