### ISSUE TITLE
Failed to include some sensitive path or file in #REQUEST-930-APPLICATION-ATTACK-LFI rules 

### ISSUE THREAD

**Issue by umarfarook882** [SpiderLabs/owasp-modsecurity-crs#814]
I have tested these payload on OWASP-CRS, It failed to block user form accessing this sensitive path or file. I have checked the rule on **REQUEST-930-APPLICATION-ATTACK-LFI** , these sensitive path or file  are not included on the lfi-os-files.data file or  on any  other rules. 

```
 #REQUEST-930-APPLICATION-ATTACK-LFI
 #PARANOIA_LEVEL:1
 #rule ID:930100,930110,930120,930130

These are the following sensitive file failed to detect by the OWASP-CRS
 /var/mail/www-data
 /etc/network/* i.e /etc/network/interfaces
 /etc/init/* i.e /etc/init/anacron.conf
```
For more information check my demo video on [Github](https://github.com/umarfarook882/WAF-Rule-Testing-LFI-attack)

**Comment by lifeforms** [comment]
Agreed! I would definitely welcome additions like `var/mail/`, `etc/network/`, `etc/init/` to the `lfi-os-files.data` file.

Even other related directories like `var/log/` might go in there. Looking at that data file, it could definitely use a lot more additions! If you feel like checking some Debian, CentOS, BSD boxes for more interesting directory hierarchies to block wholesale, I'm game...

One note for making changes to this data file: The entries should never start with a `/` since the `t:normalizePathWin` transformation may get rid of trailing slashes.

**Comment by umarfarook882** [comment]
@lifeforms Yes, sure i will update the missing directories and files for  `Debian, CentOS, BSD`  to `lfi-os-files.data`. once it done i will pull the request. Thanks for the note :)

**Comment by dune73** [comment]
Any news on this @umarfarook882?

**Comment by umarfarook882** [comment]
No, as far now we will add this below directories to `lfi-os-files.data` and close this issue.

```
var/mail/www-data
/etc/network/* 
/etc/init/*
```

**Comment by lifeforms** [comment]
Merged this PR, thanks a lot, and keep them coming! :)

**Comment by umarfarook882** [comment]
@lifeforms   Sure, Thanks for  Merging the PR :) .
