### ISSUE TITLE
False positive: SQL Hex Encoding in Cookie

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/owasp-modsecurity-crs#832]
modsec CRS v3

Rule n° 942450:
```
Rule Message: SQL Hex Encoding IdentifiedEvent:
Pattern match "(?i:(?:\\A|[^\\d])0x[a-f\\d]{3,}[a-f\\d]*)+" at 
REQUEST_COOKIES:wordpress_logged_in_9ef1dfc1z7cb62227be2b22cd13b69f2 Data:
 Matched Data: j0xddfda found within 
REQUEST_COOKIES:wordpress_logged_in_9ef1dfc1z7cb62227be2b22cd13b69f2: Vincent |1499515987|bKjyGu1pGxza4NGsxfqxoSTPA6acPA12pshj0xddfda|fea142cd4f1f746721436f9588b2c14c07f81252b2b4f1fa28a2bbd9b23eeeae
```
I guess it's a bit of bad random identifier generated by the Wp that matched this rule.

**Comment by dune73** [comment]
You are correct.

This is a PL2 rule and given the cookie name is also random, the only way for us to fight this, would be to disable the rule completely for all cookies. We think that would not be right, but it is certainly an option in your situation.

So as this is a PL2 rule, I think you need to help yourself and we won't suppress the FP in our rules. Unless @lifeforms disagrees here.

**Comment by lifeforms** [comment]
Thanks for the report! This is indeed an unfortunate false positive, which we're not able to mitigate fully in the default files, due to WordPress using random cookie names. :( You would have to do something like:

```
SecAction \
	"id:123456,phase:1,t:none,nolog,pass,\
		ctl:ruleRemoveTargetById=942450;REQUEST_COOKIES"
```

This would disable the rule for all cookies.

However, rule 942450 could trigger many other false positives too. It may be too aggressive. Maybe we can tweak it in a future release. I'll open a separate issue about that.

**Comment by ivanbaldo** [comment]
FWIW, it happens with Laravel too against REQUEST_COOKIES:XSRF-TOKEN.

**Comment by dune73** [comment]
Thank you for reporting this.
