### ISSUE TITLE
I am getting the error.log Inbound Anomaly Score Exceeded. I disabled that rule by SecRuleRemoveById  now its opening but when do xss attack Its not blocking. How to deal with anomaly?

### ISSUE THREAD

**Issue by credhats** [SpiderLabs/owasp-modsecurity-crs#864]

**Comment by spartantri** [comment]
Hi @credhats it is better if you contact the list  for generic questions (see https://coreruleset.org/support/) in order to receive some help you need to be more specific, which rule is causing you issues and what kind of content you want to send, a sample log is also quite useful.
In general removing rules is not the best idea, better adjust the anomaly scores and thresholds for your particular use case and if you need to remove a rule it is better if you do it only for the affected parameter in the affected url when the content matches what you expect (see https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecRuleUpdateTargetById)

Cheers!
