### ISSUE TITLE
Rule 93210x does not handle backticks and ) for plus'd (+) commands

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#888]
The following will not match:

```
`id`
$(id)
```

but work for other commands, e.g.:

```
`arp`
$(arp)
```

This is because id (among others) have + to avoid FPs.
`regexp-cmdline.py` does:

```
char = str.replace(char, '+', r'''(?:\s|<|>).*''')
```

That should probably be expanded to include at least ` and ).

**Comment by lifeforms** [comment]
This is intentional, using just the string `id` in this rule sadly provided many false positives on a test ruleset of common English posts. This is mentioned in the datafile regexp-932100.txt:

```
# 'id' causes way too much FP, so we require whitespace; this will allow
# injecting ';id' unfortunately.
id+
```

So just `id` is not enough to trigger the rule. Something like `$(id -A)` should match.

I would be up for hardcoding some variants of these commands. For that reason I have created a separate blacklist in `unix-shell.data`. The idea was that we could add hardcoded strings over there. I would appreciate to have stuff like:

```
`id`
$(id)
```

over there too. Would you like to add those variants to the hardcoded blacklist? (Sadly this is not a regexp list so evasion might be easy e.g. by `$(id )`, `$("id")` hence my regexp magic, but it still could catch some exploration attempts.) Keep in mind to not add strings which would have large FP risk. I guess probably the above two examples would work. Could be worth it to try to look for other words marked `+` in regexp-932100.txt and regexp-932105.txt to see if you can find some other cool candidates to add to the hardcoded blacklist.

**Comment by fgsch** [comment]
I appreciate that but I don't think $(id) or \`id` are common, hence it should be safe to add them (and any of the others, for the matter) when massaging the input.

We should be able to adjust it to some extent to catch some of the possible evasions too.

Do you see any problem with this approach?

**Comment by lifeforms** [comment]
Another more powerful approach could be to split off part of the word list to a separate rule, so that it doesn't fire on the semicolon `;id` (very common) but on other uses like `$(id)`. And then review all the commands for inclusion in that rule.

**Comment by fgsch** [comment]
This issue has timed out as it has not received any update in over 2 years.
If this is still a problem please open a new issue.
