### ISSUE TITLE
browsing with tor is blocked

### ISSUE THREAD

**Issue by quenenni** [SpiderLabs/owasp-modsecurity-crs#889]
Someone using the Os https://tails.boum.org/ and surfing through tor networks can't access its wordpress site.
The rule 953120 is triggered.

Is this because of tor browsing?

```
--a27c5e58-B--
GET / HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36
Cache-Control: no-cache
Pragma: no-cache
Host: xxxx.be
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive

--a27c5e58-F--
HTTP/1.1 412 Precondition Failed
Last-Modified: Thu, 15 Jun 2017 13:46:19 GMT
Accept-Ranges: bytes
Content-Length: 1431
Vary: Accept-Encoding,User-Agent
Cache-Control: max-age=7200, must-revalidate
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html

--a27c5e58-H--
Message: Access denied with code 412 (phase 4). Match of "rx (?:\\x1f\\x8b\\x08|\\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\\b|gif)|B(?:%pdf|\\.ra)\\b)" against "RESPONSE_BODY" required. [file "/etc/modsecurity/RESPONSE-953-DATA-LEAKAGES-PHP.conf"] [line "111"] [id "953120"] [rev "2"] [msg "PHP source code leakage"] [data "Matched Data: <? found within RESPONSE_BODY: <html>\x0a  <head>\x0a    <!-- META -->\x0a    <meta charset=\x22utf-8\x22>\x0a    <meta http-equiv=\x22X-UA-Compatible\x22 content=\x22IE=edge\x22>\x0a    <meta name=\x22viewport\x22 content=\x22width=device-width, initial-scale=1\x22>\x0a    <meta name=\x22generator\x22 content=\x22WordPress 4.8.1\x22 />\x0a    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\x0a<!-- check -->\x0a<!--\x0a    <m..."] [severity "ERROR"] [ver "OWASP_CRS/3.0.0"] [maturity "9"] [accuracy "9"] [tag "application-multi"] [tag "language-php"] [tag "platform-multi"] [tag
Message: Warning. Operator GE matched 4 at TX:outbound_anomaly_score. [file "/etc/modsecurity/RESPONSE-980-CORRELATION.conf"] [line "82"] [id "980140"] [msg "Outbound Anomaly Score Exceeded (score 4): PHP source code leakage"] [tag "event-correlation"]
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client %s] ModSecurity: %s%s [uri "%s"]%s
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client %s] ModSecurity: %s%s [uri "%s"]%s
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client %s] ModSecurity: %s%s [uri "%s"]%s
Apache-Error: [file "apache2_util.c"] [line 271] [level 3] [client %s] ModSecurity: %s%s [uri "%s"]%s
Action: Intercepted (phase 4)
Stopwatch: 1505384608842819 3558106 (- - -)
Stopwatch2: 1505384608842819 3558106; combined=123220, p1=491, p2=96167, p3=271, p4=25943, p5=303, sr=73, sw=45, l=0, gc=0
Response-Body-Transformed: Dechunked
Producer: ModSecurity for Apache/2.9.1 (http://www.modsecurity.org/); OWASP_CRS/3.0.2.
Server: Apache/2.4.10
Engine-Mode: "ENABLED"

--a27c5e58-Z--
```

**Comment by spartantri** [comment]
Hi @quenenni the 412 response comes from wordpress, the CRS does not use such status but the response matches a php leak rule so if that is normal to you you may whitelist the site on that rule or disable it entirely.
If may be better if you see the full wordpress response and take a decision based on what you see there.
As you can see on your log there is no <? in the output as it is cut to show only the first few hundred characters it is not enough to tell if it is important or not.

`<html>\x0a  <head>\x0a    <!-- META -->\x0a    <meta charset=\x22utf-8\x22>\x0a    <meta http-equiv=\x22X-UA-Compatible\x22 content=\x22IE=edge\x22>\x0a    <meta name=\x22viewport\x22 content=\x22width=device-width, initial-scale=1\x22>\x0a    <meta name=\x22generator\x22 content=\x22WordPress 4.8.1\x22 />\x0a    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\x0a<!-- check -->\x0a<!--\x0a    <m...`

Try adding auditLogPart E to the log and see there what the problem is, this may have nothing to do with the OS, browser or tor.

**Comment by quenenni** [comment]
@spartantri Thanks for your help.
412 comes from our settings in modsec.

I tried matching the regexp from the rule with the body response (https://regex101.com/) but could't find a match, so it was difficult to understand the problem (with the full  auditLogPart E).

I found someone else around me that uses the tails Os. I'll ask her to do some tests for me.

In the meantime, I'll make an exception in this rule for this website.

**Comment by YbyMMbPh** [comment]
@quenenni I think I see the reason for your confusion.
You should read rule 953120. It is a chained rule.
The first clause in the chain is `SecRule RESPONSE_BODY "<\?(?!xml)"`
This will match `<?` but not `<?xml`
The second clause in the chain is...
`SecRule RESPONSE_BODY "!(?:\x1f\x8b\x08|\b(?:(?:i(?:nterplay|hdr|d3)|m(?:ovi|thd)|r(?:ar!|iff)|(?:ex|jf)if|f(?:lv|ws)|varg|cws)\b|gif)|B(?:%pdf|\.ra)\b)"`
This is a NEGATIVE match for that regex. (which is why your response body would not match it)

The response body you have the problem with has the string `<?` in it somewhere and none of the strings from the second clause regex.
This will be due to `<?` being an intended part of the page content or an [unintended] unclosed php tag in a WordPress template file, widget or plugin.
To find it (once the exception is in place) load the page in a browser, then do a browser search for `<?`.
This will find `<?` in the content.
If nothing found the View HTML source then search for `<?`.

Confusion was due to modsec logging outputting the last regex match (which was actually a non-match)

I strongly suspect this issue has nothing to do with tor or tails Os.

**Comment by lifeforms** [comment]
This is a false positive due to `<?` appearing in output. Sometimes this happens in big binary files, which is the reason that some signatures were added to prevent false positives as @YbyMMbPh suggested. If you know the file type, let us know and we might add more signatures.

I take it, since the filename is `/`, that it's probably HTML though. The sequence could also be present due to a bug in combination with mod_deflate. However, in my experience, this bug is no longer present in recent Apache 2.4 versions. If you get this problem from time to time, upgrading Apache might also help.
