### ISSUE TITLE
Bug in rule 920420

### ISSUE THREAD

**Issue by mirkodziadzka-avi** [SpiderLabs/owasp-modsecurity-crs#898]
checked in v3.0/master and v3.1/dev

Rule 920420 does contains the line (in the last chain rule)

```
SecRule TX:0 "!^%{tx.allowed_request_content_type}$"
```

This does not work in ModSecurity, because tx variable expansions is not executed inside the Rx operator. The regular expressions are compiled during rule load time.

With the latest fix  in ModSec (https://github.com/SpiderLabs/ModSecurity/commit/039bd2cc84b2bbea2b83635ec04fef5b18622574) which fixes the handling of the negation, this rule will now fire for every content type.

**Comment by mirkodziadzka-avi** [comment]
Proposal (without having a PR or a running regression test):

Change this part of the rule to

```
SecRule TX:0 "!@within %{tx.allowed_request_content_type}"
```

**Comment by spartantri** [comment]
Hi @mirkodziadzka-avi, 
The rule does what it is supposed to do in my conf, and actually, macro expansion works in rx but it is not advised as per the reference manual ([Macro expansion](https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#Macro_Expansion)).

Regular use case with invalid Content-Type resulting in forbidden:
```
curl -XPOST http://localhost/index.html -H'Content-Type: evilpayload' -H'Content-Length: 0'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /index.html
on this server.<br />
</p>
<hr>
<address>Apache/2.4.27 (Debian) Server at localhost Port 80</address>
</body></html>

```

However this rule can be bypassed due to the issue with captures referenced in chains.
No check of duplicated headers:
```
curl -XPOST http://localhost/index.html -H'Content-Type: application/x-www-form-urlencoded' -H'Content-Type: evilpayload' -H'Content-Length: 0'
<html>Done!</html>
```

There is also another problem with the rule, it excludes GET if the Content-Lenght is 0 (otherwise 920170 will catch it) but it is possible to use chunked coding to send a body and bypass 920170 and 920410)
GET with Content-Type with Content-Length=0:
```
curl -XGET http://localhost/index.html -H'Content-Type: evilpayload' -H'Content-Length: 0'
<html>Done!</html>
```

To send request bodies you may use chunks which apparently the CRS don't recognize as valid as it complains of no Content-Lenght in POST (920180) and it doesn't care of it in GET.
GET with chunked coding sending a body with evilpayload Content-Type:
```
curl -XGET http://localhost/index.html -H'Content-Type: evilpayload' -H'Transfer-Encoding: chunked' -d @/tmp/chunk
<html>Done!</html>

```
POST with valid body using chunk with valid Content-Type resulting in forbidden:
```
curl -XPOST http://localhost/index.html -H'Content-Type: application/x-www-form-urlencoded' -H'Transfer-Encoding: chunked' -d @/tmp/chunk
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /index.html
on this server.<br />
</p>
<hr>
<address>Apache/2.4.27 (Debian) Server at localhost Port 80</address>
</body></html>
```
Valid vanila post request:
```
curl -XPOST http://localhost/index.html -H'Content-Type: application/x-www-form-urlencoded' -d @/tmp/chunk
<html>Done!</html>
```
POST using chunks resulting in forbidden:
```
curl -XPOST http://localhost/index.html -H'Transfer-Encoding: chunked' -d @/tmp/chunk
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /index.html
on this server.<br />
</p>
<hr>
<address>Apache/2.4.27 (Debian) Server at localhost Port 80</address>
</body></html>
```

**Comment by dune73** [comment]
@mirkodziadzka-avi: Do you agree or is there anything wrong with @spartantri's explanation / proof?

**Comment by mirkodziadzka-avi** [comment]
I'm still trying to find out; because I see different behaviour in our (modified) version of libmodsecurity v3 when we pulled the latest changes from upstream.  I will reproduce it with a plain modsecurity v3 installation, but for this I need more time.

I agree that the reference manual allows this (but discourage it for performance reasons).

I'm not sure if the v3 implementation will follow.

So even if this is not considered a bug, it is probably a performance issue because this regex could/must be compiled on every transaction. Using @within instead of @rx should be completely fine here and faster.

**Comment by dune73** [comment]
Oh, we're talking libmodsecurity here. That might indeed be an implementation thing then. If you can confirm the different behaviour, then please be sure to open a bug report with ModSecurity.

You have a point with the @within as opposed to @ + rx. Opinions?

**Comment by spartantri** [comment]
Did you test your proposal? to tell the perf difference with each of them?

If you can please do it and go ahead and open a PR in 3.1dev branch if there is any perf gain :)

We need more hands to add good stuff!

**Comment by mirkodziadzka-avi** [comment]
The RX problem seems to be fixed in ModSec via https://github.com/SpiderLabs/ModSecurity/issues/1528

I still think that CRS should use `@within` when possible.
