### ISSUE TITLE
FP on 942360

### ISSUE THREAD

**Issue by dune73** [SpiderLabs/owasp-modsecurity-crs#988]
`address=100 Union St.`

leads to

`942360 PL1 Detects concatenated basic SQL injection and SQLLFI attempts`

Otherwise only PL4 alerts, but this comes in the default installation.

**Comment by franbuehler** [comment]
The matching regex is: `^[\W\d]+\s*?union\b`
From: [util/regexp-assemble/regexp-942360.data](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.1/dev/util/regexp-assemble/regexp-942360.data#L44)

I searched for the string `union` over all regexp source files (this is so useful!).
It is checked for in four rules: 942190, 942260, 942360 and 942480:

```
~/git/owasp-modsecurity-crs$ grep -i union util/regexp-assemble/*
util/regexp-assemble/regexp-942190.data:[\"'`];?\s*?union\b\s*?[^\s]
util/regexp-assemble/regexp-942190.data:union select @
util/regexp-assemble/regexp-942190.data:union[\w(\s]*?select
util/regexp-assemble/regexp-942260.data:union\s*?\s*?[([]*?\s*?select\s+
util/regexp-assemble/regexp-942260.data:union\s*?all\s*?[([]*?\s*?select\s+
util/regexp-assemble/regexp-942260.data:union\s*?distinct\s*?[([]*?\s*?select\s+
util/regexp-assemble/regexp-942260.data:union\s*?[(!@]*?\s*?[([]*?\s*?select\s+
util/regexp-assemble/regexp-942360.data:^[\W\d]+\s*?union\b
util/regexp-assemble/regexp-942480.data:\bunion\b.{1,100}?\bselect\b
```

These are the messages and the paranoia levels:
```
942190: msg:'Detects MSSQL code execution and information gathering attempts' PL1
942260: msg:'Detects basic SQL authentication bypass attempts 2/3'            PL2
942360: msg:'Detects concatenated basic SQL injection and SQLLFI attempts'    PL1
942480: msg:'SQL Injection Attack'                                            PL2
```

I think we now have four possibilities:
1. Move the whole rule to PL2
2. Move the regex `^[\W\d]+\s*?union\b` to a stricter sibling 942361 on PL2 and leave rule 942360 on PL1.
3. Extend the regex with a `select` and an `all`. Example: `^[\W\d]+\s*?union\b\s*\b(all|select)`
4. Accept this FP and let it be solved by the customer, because it's a special case, an exception.

Number 1: We don't know about other FP from other regexes in this rule. If we move the whole rule, we make holes in the coverage on PL1.
Number 2: This is the simplest solution. Because of the source files, the splitting can be done easily.
Number 3: We have to agree, how exactly we want to extend the regex. As I showed above, we already have several tests with the string 'union'. Maybe we do not want another variant?
Number 4: I don't think this is a satisfying solution.

In my opinion, number 1 is the worst. Number 2 or number 3 are better. 
I think number 2 is the easiest way to solve this FP.
I will propose a PR if we agree on a solution.
